package Form;

import Database.Koneksi;
import Database.Koneksi2;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class F_Angsuran extends javax.swing.JDialog {
    
    private SimpleDateFormat frmtgl = new SimpleDateFormat("yyyy-MM-dd");
    
    public TableCellRenderer kanan = new RenderingKanan();
    public TableCellRenderer tengah = new RenderingTengah(); 
    
    public String kd_pinjaman, No_anggota, Nama, Jml_pinjam, Lama, Tot_pinjam, Tgl_pinjam, Angsuran;
    
    //Deklarasi Get
    public String getKode() {
        return kd_pinjaman;
    }
    
    public String getNo_anggota() {
        return No_anggota;
    }

    public String getNama() {
        return Nama;
    }
    
    public String getJml() {
        return Jml_pinjam;
    }
    
    public String getLama() {
        return Lama;
    }

    public String getTotal() {
        return Tot_pinjam;
    }
    
    public String getTgl() {
        return Tgl_pinjam;
    }
    
    public String getAngsuran() {
        return Angsuran;
    }
    //
    String tanggalpeminjaman,tanggalpengembalian;
    private int tglM,blnM,thnM,tglK;
    private Date tglpinjam;
    private Date tglhrskmbli;
    private Date tglkmbli;
    private String tanggalHrsKembali;
    private String tanggalKembali;
    private int iBulan;
    private String Sbulan;
    private String Kbulan;
    private int inBulan;
    private int hasilHari, hasilBulan, hasiltahun;
    //
    private DefaultTableModel model;
    String SIMPANEDIT;

    public F_Angsuran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tampil();
        tombol(true, false);
        AturText(false, false);
        
        txKdAngsuran.setEnabled(false);
        lBulan.setVisible(false);
        txJangka.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        bView = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txJmlPinjaman = new javax.swing.JTextField();
        txTotPinjaman = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txKdPinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txLama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txAngsur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txTgl_Angsur = new com.toedter.calendar.JDateChooser();
        txTgl_Pinjam = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        txBulanKe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txKdAngsuran = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rdPokok = new javax.swing.JRadioButton();
        rdJangka = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rdBunga = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        txAngsurKe = new javax.swing.JTextField();
        txSisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txBunga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txTot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txPokok = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lJangka = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txNilaiBunga = new javax.swing.JTextField();
        txJangka = new javax.swing.JTextField();
        lBulan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngsur = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        rdID = new javax.swing.JRadioButton();
        rdNama = new javax.swing.JRadioButton();
        txCari = new javax.swing.JTextField();
        bCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setText("No Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Nama Anggota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txID.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, -1));

        txNama.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 330, -1));

        bView.setText("...");
        bView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bViewActionPerformed(evt);
            }
        });
        jPanel1.add(bView, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Pinjaman");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txJmlPinjaman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txJmlPinjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txJmlPinjamanKeyTyped(evt);
            }
        });
        jPanel1.add(txJmlPinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 330, -1));

        txTotPinjaman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txTotPinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 330, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setText("Lama");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel12.setText("Total Pinjaman");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        txKdPinjam.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txKdPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setText("Kode Pinjaman");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txLama.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txLamaKeyTyped(evt);
            }
        });
        jPanel1.add(txLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 330, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel14.setText("Angsuran Pokok");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txAngsur.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txAngsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 330, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Angsuran");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txTgl_Angsur.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txTgl_AngsurPropertyChange(evt);
            }
        });
        jPanel1.add(txTgl_Angsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, -1));

        txTgl_Pinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txTgl_PinjamPropertyChange(evt);
            }
        });
        jPanel1.add(txTgl_Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel19.setText("Bulan Ke");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        txBulanKe.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txBulanKe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txBulanKePropertyChange(evt);
            }
        });
        jPanel1.add(txBulanKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setText("Kode Angsuran");

        txKdAngsuran.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rdPokok);
        rdPokok.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        rdPokok.setText("Tetap");
        rdPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPokokActionPerformed(evt);
            }
        });
        jPanel3.add(rdPokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        buttonGroup1.add(rdJangka);
        rdJangka.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        rdJangka.setText("Berjangka");
        rdJangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdJangkaActionPerformed(evt);
            }
        });
        jPanel3.add(rdJangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel13.setText("Tipe Angsuran");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(rdBunga);
        rdBunga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        rdBunga.setText("Bunga");
        rdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBungaActionPerformed(evt);
            }
        });
        jPanel3.add(rdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txAngsurKe.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txAngsurKe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txAngsurKePropertyChange(evt);
            }
        });
        txAngsurKe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAngsurKeKeyTyped(evt);
            }
        });
        jPanel4.add(txAngsurKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, -1));

        txSisa.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel4.add(txSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 310, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setText("Angsuran Bunga");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txBunga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel4.add(txBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 310, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel17.setText("Total Angsuran");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txTot.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel4.add(txTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 310, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel18.setText("Angsuran Ke");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Proses.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Proses.setText("Proses");
        Proses.setPreferredSize(new java.awt.Dimension(75, 23));
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        jPanel4.add(Proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 90, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel20.setText("Angsuran Pokok");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txPokok.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel4.add(txPokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 310, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel21.setText("Sisa Hutang");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lJangka.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lJangka.setText("%");
        jPanel4.add(lJangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel22.setText("Nilai Bunga");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txNilaiBunga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txNilaiBunga.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txNilaiBungaPropertyChange(evt);
            }
        });
        txNilaiBunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNilaiBungaKeyTyped(evt);
            }
        });
        jPanel4.add(txNilaiBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 498, 210));

        txJangka.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txJangka.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txJangkaPropertyChange(evt);
            }
        });
        txJangka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txJangkaKeyTyped(evt);
            }
        });
        jPanel3.add(txJangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 50, -1));

        lBulan.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lBulan.setText("Bulan");
        jPanel3.add(lBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bTambah.setText("TAMBAH");
        bTambah.setPreferredSize(new java.awt.Dimension(75, 23));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel5.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        bEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bEdit.setText("EDIT");
        bEdit.setPreferredSize(new java.awt.Dimension(75, 23));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel5.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 40));

        bHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.setPreferredSize(new java.awt.Dimension(75, 23));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel5.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 40));

        bSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.setPreferredSize(new java.awt.Dimension(75, 23));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel5.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 90, 40));

        bKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bKeluar.setText("KELUAR");
        bKeluar.setPreferredSize(new java.awt.Dimension(75, 23));
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel5.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 90, 40));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAngsur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAngsur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAngsurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAngsur);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 200));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Cari :");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup3.add(rdID);
        rdID.setText("ID");
        rdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdIDActionPerformed(evt);
            }
        });
        rdID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdIDKeyReleased(evt);
            }
        });
        jPanel7.add(rdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        buttonGroup3.add(rdNama);
        rdNama.setText("Nama");
        jPanel7.add(rdNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txCari.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txCariKeyReleased(evt);
            }
        });
        jPanel7.add(txCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, -1));

        bCetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bCetak.setText("Cetak Kwitansi");
        bCetak.setPreferredSize(new java.awt.Dimension(75, 23));
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(txKdAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txKdAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(bCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1112, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPokokActionPerformed
        lBulan.setVisible(false);
        txJangka.setVisible(false);
    }//GEN-LAST:event_rdPokokActionPerformed

    private void rdJangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdJangkaActionPerformed
        lBulan.setVisible(true);
        txJangka.setVisible(true);
    }//GEN-LAST:event_rdJangkaActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        AksiTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        AksiEdit();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        AksiHapus(evt);
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        AksiSimpanEdit();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        AksiKeluar(evt);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tblAngsurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAngsurMouseClicked
        MouseClicked(evt);
    }//GEN-LAST:event_tblAngsurMouseClicked

    private void bViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bViewActionPerformed
        view_ang_angsur fDB = new view_ang_angsur(null, rootPaneCheckingEnabled);
        fDB.fAG = this;
        fDB.setVisible(true);
    }//GEN-LAST:event_bViewActionPerformed

    private void txTgl_AngsurPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txTgl_AngsurPropertyChange
               
        if (txTgl_Angsur.getDate() != null) {
        SimpleDateFormat Format = new SimpleDateFormat("dd MMM yyyy");
        tanggalpengembalian = Format.format(txTgl_Angsur.getDate());
        
        int tahunH = Integer.parseInt(tanggalpeminjaman.substring(7, 11));
        int hariH = Integer.parseInt(tanggalpeminjaman.substring(0, 2));
        Sbulan = (String) tanggalpeminjaman.substring(3, 6);
        if (Sbulan.compareTo("Jan") == 0) {
            iBulan = 1;
        } else if (Sbulan.compareTo("Feb") == 0) {
            iBulan = 2;
        } else if (Sbulan.compareTo("Mar") == 0) {
            iBulan = 3;
        } else if (Sbulan.compareTo("Apr") == 0) {
            iBulan = 4;
        } else if (Sbulan.compareTo("May") == 0) {
            iBulan = 5;
        } else if (Sbulan.compareTo("Jun") == 0) {
            iBulan = 6;
        } else if (Sbulan.compareTo("Jul") == 0) {
            iBulan = 7;
        } else if (Sbulan.compareTo("Aug") == 0) {
            iBulan = 8;
        } else if (Sbulan.compareTo("Sep") == 0) {
            iBulan = 9;
        } else if (Sbulan.compareTo("Oct") == 0) {
            iBulan = 10;
        } else if (Sbulan.compareTo("Nov") == 0) {
            iBulan = 11;
        } else {
            iBulan = 12;
        }
        int tahunK = Integer.parseInt(tanggalpengembalian.substring(7, 11));
        int hariK = Integer.parseInt(tanggalpengembalian.substring(0, 2));
        Kbulan = (String) tanggalpengembalian.substring(3, 6);
        if (Kbulan.compareTo("Jan") == 0) {
            inBulan = 1;
        } else if (Kbulan.compareTo("Feb") == 0) {
            inBulan = 2;
        } else if (Kbulan.compareTo("Mar") == 0) {
            inBulan = 3;
        } else if (Kbulan.compareTo("Apr") == 0) {
            inBulan = 4;
        } else if (Kbulan.compareTo("May") == 0) {
            inBulan = 5;
        } else if (Kbulan.compareTo("Jun") == 0) {
            inBulan = 6;
        } else if (Kbulan.compareTo("Jul") == 0) {
            inBulan = 7;
        } else if (Kbulan.compareTo("Aug") == 0) {
            inBulan = 8;
        } else if (Kbulan.compareTo("Sep") == 0) {
            inBulan = 9;
        } else if (Kbulan.compareTo("Oct") == 0) {
            inBulan = 10;
        } else if (Kbulan.compareTo("Nov") == 0) {
            inBulan = 11;
        } else {
            inBulan = 12;
        }
        
            hasilHari = hariK - hariH ;
            hasilBulan = (inBulan - iBulan) * 30;
            hasiltahun = (tahunK - tahunH) * 365;
            int totalwaktu = (hasilHari + hasilBulan + hasiltahun)/30;
            txBulanKe.setText(String.valueOf(totalwaktu));
            
            
        }
        
    }//GEN-LAST:event_txTgl_AngsurPropertyChange

    private void txTgl_PinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txTgl_PinjamPropertyChange
        if (txTgl_Pinjam.getDate() != null) {
        SimpleDateFormat Format = new SimpleDateFormat("dd MMM yyyy");
            tanggalpeminjaman = Format.format(txTgl_Pinjam.getDate());
        }
    }//GEN-LAST:event_txTgl_PinjamPropertyChange

    private void txBulanKePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txBulanKePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txBulanKePropertyChange

    private void rdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBungaActionPerformed
        lBulan.setVisible(false);
        txJangka.setVisible(false);
    }//GEN-LAST:event_rdBungaActionPerformed

    private void txJmlPinjamanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txJmlPinjamanKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txJmlPinjamanKeyTyped

    private void txLamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txLamaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txLamaKeyTyped

    private void txNilaiBungaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNilaiBungaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txNilaiBungaKeyTyped

    private void txNilaiBungaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txNilaiBungaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txNilaiBungaPropertyChange

    private void txJangkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txJangkaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txJangkaKeyTyped

    private void txJangkaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txJangkaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txJangkaPropertyChange

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        int lama,ke,bulanke,jangka,angsurke;
        double  nilaibunga;
        int hutang,bunga,bunga1,angsur,sisa = 0,sisa1;
        int total,bayar;

        NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumIntegerDigits(0);
        numberFormat.setGroupingUsed(true);

        angsurke = Integer.parseInt(txAngsurKe.getText());
        
        
        hutang = Integer.parseInt(txJmlPinjaman.getText());
        lama = Integer.parseInt(txLama.getText());
        ke = Integer.parseInt(txAngsurKe.getText());
        bulanke = Integer.parseInt(txBulanKe.getText());
        nilaibunga = Double.parseDouble(txNilaiBunga.getText());

        if(txAngsurKe.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Angsuran Ke Tidak Boleh Kosong");
        }
        else if (lama < bulanke){
            int selectedOption = JOptionPane.showConfirmDialog(null, "Anda Melebihi Batas Angsuran !!!", "MAAF !!!", JOptionPane.CLOSED_OPTION);
        }
        else if ((lama == bulanke) && (lama > angsurke)){
            int selectedOption = JOptionPane.showConfirmDialog(null, "Anda Harus Melunasi Angsuran !!!", "Pelunasan", JOptionPane.CLOSED_OPTION);
        }
                   
        else
            if(rdPokok.isSelected()){
                for(int a=1;a<=ke;a++){
                    bunga = (int) ((hutang * nilaibunga)/100);
                    bayar = hutang/lama;
                    total = bayar + bunga ;
                    sisa= hutang-(hutang/lama)*a;

                    txTot.setText(numberFormat.format(total));
                    txPokok.setText(numberFormat.format(bayar));
                    txBunga.setText(numberFormat.format(bunga));
                    txSisa.setText(String.valueOf(sisa));
                    
                    if ((lama == angsurke)&& (sisa == 0)){
                        int selectedOption = JOptionPane.showConfirmDialog(null, "LUNAS", "Konfirmasi", JOptionPane.CLOSED_OPTION);
                        
                    }
                }                
            }
            else
            if(rdBunga.isSelected()){
                 
                    for(int a=1;a<=ke;a++){
                    bunga = (int) ((hutang  * nilaibunga)/100);
                    bayar = 0;
                    total = bayar + bunga;
                    sisa1= hutang -(hutang/lama)*a;
                    sisa=sisa1 + (hutang/lama);

                    txTot.setText(numberFormat.format(total));
                    txPokok.setText(numberFormat.format(bayar));
                    txBunga.setText(numberFormat.format(bunga));
                    txSisa.setText(String.valueOf(sisa));
                    }                
                 if ((lama == angsurke) && (sisa != 0)){
                        int selectedOption = JOptionPane.showConfirmDialog(null, "Anda Harus Melunasi Angsuran Atau Perpanjang Pinjaman !!!", "MAAF !!!", JOptionPane.CLOSED_OPTION);
                        bersih();
                     }
                 
                 
            }
            else
            {
                if(txJangka.getText().equals("")){
                    JOptionPane.showMessageDialog(rootPane, "Jangka Tidak Boleh Kosong");
                }
                else{
                    jangka = Integer.parseInt(txJangka.getText());
                    for(int a=1;a<=ke;a++){
                        bunga = (int) ((hutang * nilaibunga)/100);
                        bayar = jangka * (hutang/lama);
                        total = bayar + bunga ;
                        sisa= hutang-(hutang/lama)*a;

                        txTot.setText(numberFormat.format(total));
                        txPokok.setText(numberFormat.format(bayar));
                        txBunga.setText(numberFormat.format(bunga));
                        txSisa.setText(String.valueOf(sisa));
                        
                        
                        if (lama == bulanke){
                            int selectedOption = JOptionPane.showConfirmDialog(null, "LUNAS", "Konfirmasi", JOptionPane.CLOSED_OPTION);
                            
                        }
                    }                    
                }
            }  
        
    }//GEN-LAST:event_ProsesActionPerformed

    private void txAngsurKeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAngsurKeKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txAngsurKeKeyTyped

    private void txAngsurKePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txAngsurKePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txAngsurKePropertyChange

    private void rdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdIDActionPerformed

    }//GEN-LAST:event_rdIDActionPerformed

    private void rdIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdIDKeyReleased

    }//GEN-LAST:event_rdIDKeyReleased

    private void txCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCariKeyReleased
        if (rdID.isSelected()){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode");
            tbl.addColumn("Tanggal Pinjam");
            tbl.addColumn("Tgl. Angsur");
            tbl.addColumn("Kode Pinjaman");
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Jumlah");
            tbl.addColumn("Lama");
            tbl.addColumn("Total Pinjam");
            tbl.addColumn("Angsuran"); 
            tbl.addColumn("Bln. Ke"); 
            tbl.addColumn("Tipe"); 
            tbl.addColumn("Angsur Ke"); 
            tbl.addColumn("Sisa"); 
            tbl.addColumn("Pokok"); 
            tbl.addColumn("Bunga");
            tbl.addColumn("Total");
            tblAngsur.setModel(tbl);
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT * FROM t_angsuran WHERE Kd_Angsuran LIKE '"+txCari.getText()+"%'");
                while (res.next()) 
                {
                    tbl.addRow(new Object[]{
                        res.getString("Kd_Angsuran"),
                        res.getDate("Tgl_pinjam"),
                        res.getDate("Tgl_Angsur"),
                        res.getString("kd_pinjaman"),
                        res.getString("No_anggota"),
                        res.getString("Nama"),
                        res.getString("Jml_pinjam"),
                        res.getString("Lama"),
                        res.getString("Tot_pinjaman"),
                        res.getString("Angsuran"),
                        res.getString("Bulan_ke"),
                        res.getString("Tipe"),
                        res.getString("Angsuran_ke"),
                        res.getString("Sisa"),
                        res.getString("Pokok"),
                        res.getString("Bunga"),
                        res.getString("Total_Angsur"),
                    });
                    tblAngsur.setModel(tbl);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
        if (rdNama.isSelected()){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode");
            tbl.addColumn("Tanggal Pinjam");
            tbl.addColumn("Tgl. Angsur");
            tbl.addColumn("Kode Pinjaman");
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Jumlah");
            tbl.addColumn("Lama");
            tbl.addColumn("Total Pinjam");
            tbl.addColumn("Angsuran"); 
            tbl.addColumn("Bln. Ke"); 
            tbl.addColumn("Tipe"); 
            tbl.addColumn("Angsur Ke"); 
            tbl.addColumn("Sisa"); 
            tbl.addColumn("Pokok"); 
            tbl.addColumn("Bunga");
            tbl.addColumn("Total");
            tblAngsur.setModel(tbl);
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT * FROM t_angsuran WHERE Nama LIKE '"+txCari.getText()+"%'");
                while (res.next()) 
                {
                    tbl.addRow(new Object[]{
                        res.getString("Kd_Angsuran"),
                        res.getDate("Tgl_pinjam"),
                        res.getDate("Tgl_Angsur"),
                        res.getString("kd_pinjaman"),
                        res.getString("No_anggota"),
                        res.getString("Nama"),
                        res.getString("Jml_pinjam"),
                        res.getString("Lama"),
                        res.getString("Tot_pinjaman"),
                        res.getString("Angsuran"),
                        res.getString("Bulan_ke"),
                        res.getString("Tipe"),
                        res.getString("Angsuran_ke"),
                        res.getString("Sisa"),
                        res.getString("Pokok"),
                        res.getString("Bunga"),
                        res.getString("Total_Angsur"),
                    });
                    tblAngsur.setModel(tbl);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
    }//GEN-LAST:event_txCariKeyReleased

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        if(txKdAngsuran.getText().isEmpty()){
            int selectedOption = JOptionPane.showConfirmDialog(null, "Pilih Data ", "Konfirmasi !!!", JOptionPane.CLOSED_OPTION);
        }
        else {
            cetak();
        }
    }//GEN-LAST:event_bCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_Angsuran dialog = new F_Angsuran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proses;
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBulan;
    private javax.swing.JLabel lJangka;
    private javax.swing.JRadioButton rdBunga;
    private javax.swing.JRadioButton rdID;
    private javax.swing.JRadioButton rdJangka;
    private javax.swing.JRadioButton rdNama;
    private javax.swing.JRadioButton rdPokok;
    private javax.swing.JTable tblAngsur;
    private javax.swing.JTextField txAngsur;
    private javax.swing.JTextField txAngsurKe;
    private javax.swing.JTextField txBulanKe;
    private javax.swing.JTextField txBunga;
    private javax.swing.JTextField txCari;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txJangka;
    private javax.swing.JTextField txJmlPinjaman;
    private javax.swing.JTextField txKdAngsuran;
    private javax.swing.JTextField txKdPinjam;
    private javax.swing.JTextField txLama;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNilaiBunga;
    private javax.swing.JTextField txPokok;
    private javax.swing.JTextField txSisa;
    private com.toedter.calendar.JDateChooser txTgl_Angsur;
    private com.toedter.calendar.JDateChooser txTgl_Pinjam;
    private javax.swing.JTextField txTot;
    private javax.swing.JTextField txTotPinjaman;
    // End of variables declaration//GEN-END:variables

    void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode");
        tbl.addColumn("Tanggal Pinjam");
        tbl.addColumn("Tgl. Angsur");
        tbl.addColumn("Kode Pinjaman");
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Lama");
        tbl.addColumn("Total Pinjam");
        tbl.addColumn("Angsuran"); 
        tbl.addColumn("Bln. Ke"); 
        tbl.addColumn("Tipe"); 
        tbl.addColumn("Angsur Ke"); 
        tbl.addColumn("Sisa"); 
        tbl.addColumn("Pokok"); 
        tbl.addColumn("Bunga");
        tbl.addColumn("Total");
        tblAngsur.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("Select * from t_angsuran");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getString("Kd_Angsuran"),
                    res.getDate("Tgl_pinjam"),
                    res.getDate("Tgl_Angsur"),
                    res.getString("kd_pinjaman"),
                    res.getString("No_anggota"),
                    res.getString("Nama"),
                    res.getString("Jml_pinjam"),
                    res.getString("Lama"),
                    res.getString("Tot_pinjaman"),
                    res.getString("Angsuran"),
                    res.getString("Bulan_ke"),
                    res.getString("Tipe"),
                    res.getString("Angsuran_ke"),
                    res.getString("Sisa"),
                    res.getString("Pokok"),
                    res.getString("Bunga"),
                    res.getString("Total_Angsur"),
                });
                tblAngsur.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            tblAngsur.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblAngsur.getColumnModel().getColumn(0).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(1).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblAngsur.getColumnModel().getColumn(2).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(3).setPreferredWidth(500);
            tblAngsur.getColumnModel().getColumn(3).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(4).setPreferredWidth(300);
            tblAngsur.getColumnModel().getColumn(4).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(5).setPreferredWidth(200);
            tblAngsur.getColumnModel().getColumn(6).setPreferredWidth(300);
            tblAngsur.getColumnModel().getColumn(6).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(7).setPreferredWidth(200);
            tblAngsur.getColumnModel().getColumn(7).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(8).setPreferredWidth(200);
            tblAngsur.getColumnModel().getColumn(8).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(9).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(9).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(10).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(10).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(11).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(11).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(12).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(12).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(13).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(13).setCellRenderer(tengah);
            tblAngsur.getColumnModel().getColumn(14).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(14).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(15).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(15).setCellRenderer(kanan);
            tblAngsur.getColumnModel().getColumn(16).setPreferredWidth(400);
            tblAngsur.getColumnModel().getColumn(16).setCellRenderer(kanan);
    }
    
    void tombol(boolean a,boolean b){
        bTambah.setEnabled(a);
        bEdit.setEnabled(a);
        bHapus.setEnabled(a);
        bSimpan.setEnabled(b);
        bView.setEnabled(b);
        Proses.setEnabled(b);
    }
    
    void bersih(){
        //txKdAngsuran.setText("");
        txTgl_Pinjam.setDate(null);
        txTgl_Angsur.setDate(null);
        txKdPinjam.setText("");
        txID.setText("");
        txNama.setText("");
        txJmlPinjaman.setText("");
        txLama.setText("");
        txTotPinjaman.setText("");
        txTot.setText("");
        txAngsur.setText("");
        txBulanKe.setText("");
        txAngsurKe.setText("");
        txJangka.setText("");
        txNilaiBunga.setText("");
        txSisa.setText("");
        txPokok.setText("");
        txBunga.setText("");
    }
    
    void AturText(boolean atur, boolean atur1){
        //txKdAngsuran.setEnabled(atur);
        txTgl_Pinjam.setEnabled(atur1);
        txTgl_Angsur.setEnabled(atur);
        txKdPinjam.setEnabled(atur1);
        txID.setEnabled(atur1);
        txNama.setEnabled(atur1);
        txJmlPinjaman.setEnabled(atur1);
        txLama.setEnabled(atur1);
        txTotPinjaman.setEnabled(atur1);
        txTot.setEnabled(atur1);
        txAngsur.setEnabled(atur1);
        txBulanKe.setEnabled(atur1);
        txAngsurKe.setEnabled(atur);
        txJangka.setEnabled(atur);
        txNilaiBunga.setEnabled(atur);
        txPokok.setEnabled(atur1);
        txSisa.setEnabled(atur1);
        txBunga.setEnabled(atur1);
    }
    
    
    void AksiTambah(){
        SIMPANEDIT = "Add";
        //noUrut();
        ID();
        bersih();
        tombol(false, true);
        AturText(true, false);
        bKeluar.setText("BATAL");
        //tblAngsur.setVisible(false);
    }
    
    void AksiEdit(){
        if(txKdAngsuran.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Rubah");
        }
        else{
            SIMPANEDIT = "Edit";
            tombol(false, true);
            AturText(true, false);
            bKeluar.setText("BATAL");
            tblAngsur.setVisible(false);
        }        
    }
    
    void AksiHapus(java.awt.event.ActionEvent evt){
        if(txKdAngsuran.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Hapus");
        }
        else{
            int selectedOption = JOptionPane.showConfirmDialog(null, "Yakin anda akan menghapus ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                try {
                    Statement statement=(Statement)Koneksi.GetConnection().createStatement();String sql = "DELETE FROM t_angsuran WHERE Kd_Angsuran = '"+txKdAngsuran.getText()+"';";                    
                    statement.executeUpdate(sql);
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    bersih();
                    tombol(true, false);
                    txKdAngsuran.setText("");
                } catch (Exception DBException) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus " + DBException);
                    bersih();
                }
            }            
            tampil();
        }
    }
           
    void AksiKeluar(java.awt.event.ActionEvent evt){
        if(bKeluar.getText().equals("KELUAR")){
            dispose();
        }
        else{
            txKdAngsuran.setText("");
            txAngsurKe.setText("");
            AturText(false, false);
            bKeluar.setText("KELUAR");
            tombol(true, false);
            tblAngsur.setVisible(true);
            bersih();
        }
    }
    
    void MouseClicked(java.awt.event.MouseEvent evt){
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            int row = tblAngsur.rowAtPoint(evt.getPoint());
            
            String Kd_Angsuran = tblAngsur.getValueAt(row, 0).toString();
            String Tgl_pinjam = tblAngsur.getValueAt(row, 1).toString();
            String Tgl_Angsur = tblAngsur.getValueAt(row, 2).toString();
            String kd_pinjaman = tblAngsur.getValueAt(row, 3).toString();
            String No_Anggota = tblAngsur.getValueAt(row, 4).toString();
            String Nama = tblAngsur.getValueAt(row, 5).toString();
            String Jml_pinjam = tblAngsur.getValueAt(row, 6).toString();
            String Lama = tblAngsur.getValueAt(row, 7).toString();
            String Tot_pinjaman = tblAngsur.getValueAt(row, 8).toString();
            String Angsuran = tblAngsur.getValueAt(row, 9).toString();
            String Bulan_ke = tblAngsur.getValueAt(row, 10).toString();
            String Tipe = tblAngsur.getValueAt(row, 11).toString();
            String Angsuran_ke = tblAngsur.getValueAt(row, 12).toString();
            String Sisa = tblAngsur.getValueAt(row, 13).toString();
            String Pokok = tblAngsur.getValueAt(row, 14).toString();
            String Bunga = tblAngsur.getValueAt(row, 15).toString();
            String Total_Angsur = tblAngsur.getValueAt(row, 16).toString();
                        
            txKdAngsuran.setText(String.valueOf(Kd_Angsuran));
            txTgl_Pinjam.setDate(java.sql.Date.valueOf(Tgl_pinjam));
            txTgl_Angsur.setDate(java.sql.Date.valueOf(Tgl_Angsur));
            txKdPinjam.setText(String.valueOf(kd_pinjaman));
            txID.setText(String.valueOf(No_Anggota));
            txNama.setText(String.valueOf(Nama));
            txJmlPinjaman.setText(String.valueOf(Jml_pinjam));
            txLama.setText(String.valueOf(Lama));
            txTotPinjaman.setText(String.valueOf(Tot_pinjaman));
            txAngsur.setText(String.valueOf(Angsuran));
            txBulanKe.setText(String.valueOf(Bulan_ke));
            //txBulanKe.setText(String.valueOf(Tipe));
            txAngsurKe.setText(String.valueOf(Angsuran_ke));
            txSisa.setText(String.valueOf(Sisa));
            txPokok.setText(String.valueOf(Pokok));
            txBunga.setText(String.valueOf(Bunga));
            txTot.setText(String.valueOf(Total_Angsur));
            } catch (Exception e) {
        }
    }
   
    void noUrut(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql ="SELECT MAX(right(Kd_Angsuran,1)) FROM t_angsuran";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first()==false){
                txKdAngsuran.setText("KPA-1");
            }
            else{
                rs.last();
                int no=rs.getInt(1)+1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i = 0; i < 2-pjg_cno; i++) {
                    cno=""+cno;
                }
                txKdAngsuran.setText("KPA-"+ cno);
            }
        } catch (Exception e) {
            System.err.println("Error = "+ e);
        }
    }
    
    public void itemTerpilih(){
        view_ang_angsur fDB = new view_ang_angsur(null, rootPaneCheckingEnabled);
        fDB.fAG = this;
        txKdPinjam.setText(kd_pinjaman);
        txID.setText(No_anggota);
        txNama.setText(Nama);
        txJmlPinjaman.setText(Jml_pinjam);
        txLama.setText(Lama);
        txTotPinjaman.setText(Tot_pinjam);
        txTgl_Pinjam.setDate(java.sql.Date.valueOf(Tgl_pinjam));
        txAngsur.setText(Angsuran);
    }
    
    void AksiSimpanEdit(){
        String Tipe = null;
        
        if (rdPokok.isSelected()){
            Tipe = "Pokok";
        }
        else if (rdBunga.isSelected()){
            Tipe = "Bunga";
        }
        else if (rdJangka.isSelected()){
            Tipe = "Jangka";
        }
        
        tblAngsur.setVisible(true);
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txTgl_Angsur.getDate()));

        String tmp ="yyyy-MM-dd";
        SimpleDateFormat fn = new SimpleDateFormat(tmp);
        String tanggal1 = String.valueOf(fn.format(txTgl_Pinjam.getDate()));
                
        if (SIMPANEDIT.equalsIgnoreCase("Add")){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "INSERT INTO t_angsuran(Kd_Angsuran,Tgl_Angsur, Tgl_pinjam,kd_pinjaman, No_anggota,Nama,Jml_pinjam,Lama,Tot_pinjaman,Angsuran,Bulan_ke,Tipe,Angsuran_ke,Sisa,Pokok,Bunga,Total_Angsur) "
                        + "VALUES ('"+txKdAngsuran.getText()+"','"+tanggal+"','"+tanggal1+"','"+txKdPinjam.getText()+"','"+txID.getText()+"','"+txNama.getText()+"','"+txJmlPinjaman.getText()+"',"
                        + "'"+txLama.getText()+"','"+txTotPinjaman.getText()+"','"+txAngsur.getText()+"','"+txBulanKe.getText()+"','"+Tipe+"','"+txAngsurKe.getText()+"',"
                        + "'"+txSisa.getText()+"','"+txPokok.getText()+"','"+txBunga.getText()+"','"+txTot.getText()+"')";
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                cetak();
                txKdAngsuran.setText("");
                bersih();
                AturText(false, false);
                tombol(true, false);
                bKeluar.setText("KELUAR");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }
        }
        else{
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "UPDATE t_angsuran SET Tgl_Angsur = '" +tanggal1+"',"
                        + "Tgl_Angsur = '" + tanggal+"',"
                        + "kd_pinjaman = '" + txKdPinjam.getText()+"',"
                        + "No_anggota = '" + txID.getText()+"',"
                        + "Nama = '" + txNama.getText()+"',"
                        + "Jml_pinjam = '" + txJmlPinjaman.getText()+"',"
                        + "Lama = '" + txLama.getText()+"',"
                        + "Tot_pinjaman = '" + txTotPinjaman.getText()+"',"
                        + "Angsuran = '" + txAngsur.getText()+"',"
                        + "Bulan_ke = '" + txBulanKe.getText()+"',"
                        + "Tipe = '" + Tipe+"',"
                        + "Angsuran_ke = '" + txAngsurKe.getText()+"',"
                        + "Sisa = '" + txSisa.getText()+"',"
                        + "Pokok = '" + txPokok.getText()+"',"
                        + "Bunga = '" + txBunga.getText()+"',"
                        + "Total_Angsur= '" + txTot.getText()+"'"
                        + "WHERE Kd_Angsuran = '"+txKdAngsuran.getText()+"'";                    
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Rubah");
                bersih();
                AturText(false,false);
                tombol(true, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Rubah" + e);
            }
        }
    }
    
    void tglhariini(){
    }
    
     void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
        }
    }
     
    void cetak(){
        try {
                   String path = System.getProperty ("user.dir") +"/src/Report/LAngsuranPerAnggota.jasper";
                  //  File file=new File("src/nyobarepotlagi/report1.jrxml");
                  //  JasperDesign jasperdesign=JRXmlLoader.load(file);
                    HashMap parameter = new HashMap();
                    parameter.put("Kd_Angsur", txKdAngsuran.getText());
                   // JasperReport jasperreport=JasperCompileManager.compileReport(jasperdesign);
                    JasperPrint print = JasperFillManager.fillReport(path, parameter, Koneksi2.getkoneksi());
                    JasperViewer.viewReport(print, false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
            }
    }
    
    void ID(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql = "SELECT MAX(right(Kd_Angsuran,5)) AS no FROM t_angsuran";
            ResultSet rs = statement.executeQuery(sql);
            
            while(rs.next())
            {
                if(rs.first() == false)
                {
                txKdAngsuran.setText("KP-000001");
            }
                else
            {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<6-noLong;a++)
                    { 
                        no = "0" + no;
                    }
                   txKdAngsuran.setText("KP-" + no);
                 }        
            }
       rs.close();
        } catch (Exception e) {
        }
    }
}
