package Form;

import Database.Koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

public class F_Pengurus extends javax.swing.JDialog {

    private DefaultTableModel model;
    String SIMPANEDIT;
    
    public F_Pengurus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tampil();
        bersih();
        tombol(true, false);
        AturText(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txKdPengurus = new javax.swing.JTextField();
        txKetua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txWakil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txSekretaris = new javax.swing.JTextField();
        txBendahara = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPengurus = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setText("No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txKdPengurus.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txKdPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, -1));

        txKetua.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txKetua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setText("Ketua");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txWakil.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txWakil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setText("Wakil Ketua");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Sekretaris");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txSekretaris.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txSekretaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 210, -1));

        txBendahara.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txBendahara, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setText("Bendahara");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 364, 174));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblPengurus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblPengurus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPengurusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPengurus);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 364, 148));

        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        bEdit.setText("EDIT");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 196, -1, -1));

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 196, -1, -1));

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 196, -1, -1));

        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 196, -1, -1));

        setSize(new java.awt.Dimension(400, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        AksiTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        AksiEdit();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        AksiHapus(evt);
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        AksiSimpanEdit(evt);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        AksiKeluar(evt);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void TblPengurusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPengurusMouseClicked
        MouseClik(evt);
    }//GEN-LAST:event_TblPengurusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_Pengurus dialog = new F_Pengurus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPengurus;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txBendahara;
    private javax.swing.JTextField txKdPengurus;
    private javax.swing.JTextField txKetua;
    private javax.swing.JTextField txSekretaris;
    private javax.swing.JTextField txWakil;
    // End of variables declaration//GEN-END:variables

    void bersih(){
        txKdPengurus.setText("");
        txKetua.setText("");
        txWakil.setText("");
        txSekretaris.setText("");
        txBendahara.setText("");
    }
    
    void tombol(boolean a,boolean b){
        bTambah.setEnabled(a);
        bEdit.setEnabled(a);
        bHapus.setEnabled(a);
        bSimpan.setEnabled(b);
    }
    void AturText(boolean atur){
        txKdPengurus.setEnabled(atur);
        txKetua.setEnabled(atur);
        txWakil.setEnabled(atur);
        txSekretaris.setEnabled(atur);
        txBendahara.setEnabled(atur);
    }
    
    void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No"); 
        tbl.addColumn("Ketua"); 
        tbl.addColumn("Wakil"); 
        tbl.addColumn("Sekretaris"); 
        tbl.addColumn("Bendahara"); 
        TblPengurus.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("Select * from t_pengurus");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getString("No_Peng"),
                    res.getString("Ketua"),
                    res.getString("Wakil"),
                    res.getString("Sekretaris"),
                    res.getString("Bendahara"),
                });
                TblPengurus.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            TblPengurus.getColumnModel().getColumn(0).setPreferredWidth(100);
            TblPengurus.getColumnModel().getColumn(1).setPreferredWidth(500);
            TblPengurus.getColumnModel().getColumn(2).setPreferredWidth(500);
            TblPengurus.getColumnModel().getColumn(3).setPreferredWidth(500);
            TblPengurus.getColumnModel().getColumn(4).setPreferredWidth(500);
    }
    
    void AksiSimpanEdit(java.awt.event.ActionEvent evt){
        TblPengurus.setVisible(true);
        
        if (SIMPANEDIT.equalsIgnoreCase("Add")){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "INSERT INTO t_pengurus(No_Peng,Ketua,Wakil,Sekretaris,Bendahara) "
                        + "VALUES ('"+txKdPengurus.getText()+"','"+txKetua.getText()+"','"+txWakil.getText()+"','"+txSekretaris.getText()+"','"+txBendahara.getText()+"')";
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                bersih();
                AturText(false);
                tombol(true, false);
                bKeluar.setText("KELUAR");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }
        }
        else{
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "UPDATE t_pengurus SET Ketua = '" +txKetua.getText()+"',"
                        + "Wakil = '"+txWakil.getText()+"',"                    
                        + "Sekretaris = '"+txSekretaris.getText()+"',"                    
                        + "Bendahara = '"+txBendahara.getText()+"'"                    
                        + "WHERE No_Peng = '"+txKdPengurus.getText()+"'";                    
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Rubah");
                bersih();
                AturText(false);
                tombol(true, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Rubah" + e);
            }
        }
    }
    
    void AksiHapus(java.awt.event.ActionEvent evt){
        if(txKdPengurus.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Hapus");
        }
        else{
            int selectedOption = JOptionPane.showConfirmDialog(null, "Yakin anda akan menghapus ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                try {
                    Statement statement=(Statement)Koneksi.GetConnection().createStatement();

                    String sql = "DELETE FROM t_pengurus WHERE No_Peng = '"+txKdPengurus.getText()+"';";                    
                    statement.executeUpdate(sql);
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    bersih();
                    tombol(true, false);
                } catch (Exception DBException) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus " + DBException);
                    bersih();
                }
            }            
            tampil();
        }
    }
    
    void AksiKeluar(java.awt.event.ActionEvent evt){
        if(bKeluar.getText().equals("KELUAR")){
            dispose();
        }
        else{
            AturText(false);
            bKeluar.setText("KELUAR");
            tombol(true, false);
            TblPengurus.setVisible(true);
            bersih();
        }
    }
    void AksiTambah(){
        SIMPANEDIT = "Add";
        bersih();
        tombol(false, true);
        AturText(true);
        bKeluar.setText("BATAL");
        TblPengurus.setVisible(false);
    }
    
    void AksiEdit(){
        if(txKdPengurus.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Rubah");
        }
        else{
            SIMPANEDIT = "Edit";
            tombol(false, true);
            AturText(true);
            bKeluar.setText("BATAL");
            TblPengurus.setVisible(false);
        }        
    }
    
    void MouseClik(java.awt.event.MouseEvent evt){
        try {
            int row = TblPengurus.rowAtPoint(evt.getPoint());

            String No_Peng = TblPengurus.getValueAt(row, 0).toString();            
            String Ketua = TblPengurus.getValueAt(row, 1).toString();            
            String Wakil = TblPengurus.getValueAt(row, 2).toString();            
            String Sekretaris = TblPengurus.getValueAt(row, 3).toString();            
            String Bendahara = TblPengurus.getValueAt(row, 4).toString();            
            
            txKdPengurus.setText(String.valueOf(No_Peng));
            txKetua.setText(String.valueOf(Ketua));
            txWakil.setText(String.valueOf(Wakil));
            txSekretaris.setText(String.valueOf(Sekretaris));
            txBendahara.setText(String.valueOf(Bendahara));
            } catch (Exception e) {
        }        
    }
}
