/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Database.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author KEEN-JAVA
 */
public class F_PinjamanBaru extends javax.swing.JDialog {

    public TableCellRenderer kanan = new RenderingKanan();
    public TableCellRenderer tengah = new RenderingTengah();
    
    public String kd_pinjaman,No_anggota, Nama, Pinjam;
    
    //Deklarasi Get
    public String getkd_pinjaman() {
        return kd_pinjaman;
    }
    
    public String getNo_anggota() {
        return No_anggota;
    }

    public String getNama() {
        return Nama;
    }
    
    public String Pinjam() {
        return Pinjam;
    }
    
    String tanggalpeminjaman,tanggalpengembalian;
    private int tglM,blnM,thnM,tglK;
    private Date tglpinjam;
    private Date tglhrskmbli;
    private Date tglkmbli;
    private String tanggalHrsKembali;
    private String tanggalKembali;
    private int iBulan;
    private String Sbulan;
    private String Kbulan;
    private int inBulan;
    private int hasilHari, hasilBulan, hasiltahun;
    
    
    
    private DefaultTableModel model;
    String SIMPANEDIT;
    
    public F_PinjamanBaru(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tampil();
        bersih();
        tombol(true, false);
        AturText(false);
        
        txKdPinjaman.setEnabled(false);
        txID.setEnabled(false);
        txNama.setEnabled(false);
        txSisa.setEnabled(false);
        txBunga2.setEnabled(false);       
        txTot.setEnabled(false);       
        txNonbunga.setEnabled(false);       
        txAngsuran.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txKdPinjaman = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txView = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txJmlPinjaman = new javax.swing.JTextField();
        txSisa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txPinjBaru = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bHitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txAngsuran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txNonbunga = new javax.swing.JTextField();
        txLama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txTot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txBunga = new javax.swing.JTextField();
        txBunga2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttglpinjam = new com.toedter.calendar.JDateChooser();
        txttanggalkembali = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setText("Kode Pinjaman");

        txKdPinjaman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setName("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setText("No Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Nama Anggota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txID.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 210, -1));

        txNama.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 260, -1));

        txView.setText("...");
        txView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txViewActionPerformed(evt);
            }
        });
        jPanel1.add(txView, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 40, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Pinjaman");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txJmlPinjaman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txJmlPinjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txJmlPinjamanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txJmlPinjamanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txJmlPinjamanKeyTyped(evt);
            }
        });
        jPanel1.add(txJmlPinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 260, -1));

        txSisa.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 260, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel14.setText("Sisa Pinjaman");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txPinjBaru.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txPinjBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPinjBaruKeyTyped(evt);
            }
        });
        jPanel1.add(txPinjBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 260, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel15.setText("Pinjaman Baru");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        bHitung.setText("HITUNG");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        jPanel1.add(bHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel8.setText("Angsuran Pokok");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txAngsuran.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel2.add(txAngsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 290, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setText("Non Bunga");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txNonbunga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txNonbunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNonbungaKeyPressed(evt);
            }
        });
        jPanel2.add(txNonbunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 290, -1));

        txLama.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txLamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txLamaKeyTyped(evt);
            }
        });
        jPanel2.add(txLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 95, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel9.setText("Bulan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setText("Lama Pinjaman");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel12.setText("Total Pinjaman");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txTot.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txTot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTotKeyPressed(evt);
            }
        });
        jPanel2.add(txTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 290, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel7.setText("Bunga %");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txBunga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBungaActionPerformed(evt);
            }
        });
        txBunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBungaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBungaKeyTyped(evt);
            }
        });
        jPanel2.add(txBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, -1));

        txBunga2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txBunga2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBunga2KeyPressed(evt);
            }
        });
        jPanel2.add(txBunga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Pinjam");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel13.setText("Tanggal Jatuh Tempo");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txttglpinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txttglpinjamPropertyChange(evt);
            }
        });
        jPanel2.add(txttglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, -1));

        txttanggalkembali.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txttanggalkembaliAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txttanggalkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txttanggalkembaliPropertyChange(evt);
            }
        });
        jPanel2.add(txttanggalkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bTambah.setText("TAMBAH");
        bTambah.setPreferredSize(new java.awt.Dimension(75, 23));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel4.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        bEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bEdit.setText("EDIT");
        bEdit.setPreferredSize(new java.awt.Dimension(75, 23));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel4.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 40));

        bHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.setPreferredSize(new java.awt.Dimension(75, 23));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel4.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 40));

        bSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.setPreferredSize(new java.awt.Dimension(75, 23));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 40));

        bKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bKeluar.setText("KELUAR");
        bKeluar.setPreferredSize(new java.awt.Dimension(75, 23));
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel4.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPinjam);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(txKdPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txKdPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(936, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txViewActionPerformed
        view_pinjamBaru fBR = new view_pinjamBaru(null, rootPaneCheckingEnabled);
        fBR.fBU = this;
        fBR.setVisible(true);
    }//GEN-LAST:event_txViewActionPerformed

    private void txJmlPinjamanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txJmlPinjamanKeyPressed

    }//GEN-LAST:event_txJmlPinjamanKeyPressed

    private void txJmlPinjamanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txJmlPinjamanKeyReleased

    }//GEN-LAST:event_txJmlPinjamanKeyReleased

    private void txJmlPinjamanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txJmlPinjamanKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txJmlPinjamanKeyTyped

    private void txttglpinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txttglpinjamPropertyChange
        if (txttglpinjam.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("dd MMM yyyy");
            tanggalpeminjaman = Format.format(txttglpinjam.getDate());
        }
    }//GEN-LAST:event_txttglpinjamPropertyChange

    private void txttanggalkembaliAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txttanggalkembaliAncestorAdded

    }//GEN-LAST:event_txttanggalkembaliAncestorAdded

    private void txttanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txttanggalkembaliPropertyChange

        if (txttanggalkembali.getDate() != null) {
            SimpleDateFormat Format = new SimpleDateFormat("dd MMM yyyy");
            tanggalpengembalian = Format.format(txttanggalkembali.getDate());

            int tahunH = Integer.parseInt(tanggalpeminjaman.substring(7, 11));
            int hariH = Integer.parseInt(tanggalpeminjaman.substring(0, 2));
            Sbulan = (String) tanggalpeminjaman.substring(3, 6);
            if (Sbulan.compareTo("Jan") == 0) {
                iBulan = 1;
            } else if (Sbulan.compareTo("Feb") == 0) {
                iBulan = 2;
            } else if (Sbulan.compareTo("Mar") == 0) {
                iBulan = 3;
            } else if (Sbulan.compareTo("Apr") == 0) {
                iBulan = 4;
            } else if (Sbulan.compareTo("May") == 0) {
                iBulan = 5;
            } else if (Sbulan.compareTo("Jun") == 0) {
                iBulan = 6;
            } else if (Sbulan.compareTo("Jul") == 0) {
                iBulan = 7;
            } else if (Sbulan.compareTo("Aug") == 0) {
                iBulan = 8;
            } else if (Sbulan.compareTo("Sep") == 0) {
                iBulan = 9;
            } else if (Sbulan.compareTo("Oct") == 0) {
                iBulan = 10;
            } else if (Sbulan.compareTo("Nov") == 0) {
                iBulan = 11;
            } else {
                iBulan = 12;
            }
            int tahunK = Integer.parseInt(tanggalpengembalian.substring(7, 11));
            int hariK = Integer.parseInt(tanggalpengembalian.substring(0, 2));
            Kbulan = (String) tanggalpengembalian.substring(3, 6);
            if (Kbulan.compareTo("Jan") == 0) {
                inBulan = 1;
            } else if (Kbulan.compareTo("Feb") == 0) {
                inBulan = 2;
            } else if (Kbulan.compareTo("Mar") == 0) {
                inBulan = 3;
            } else if (Kbulan.compareTo("Apr") == 0) {
                inBulan = 4;
            } else if (Kbulan.compareTo("May") == 0) {
                inBulan = 5;
            } else if (Kbulan.compareTo("Jun") == 0) {
                inBulan = 6;
            } else if (Kbulan.compareTo("Jul") == 0) {
                inBulan = 7;
            } else if (Kbulan.compareTo("Aug") == 0) {
                inBulan = 8;
            } else if (Kbulan.compareTo("Sep") == 0) {
                inBulan = 9;
            } else if (Kbulan.compareTo("Oct") == 0) {
                inBulan = 10;
            } else if (Kbulan.compareTo("Nov") == 0) {
                inBulan = 11;
            } else {
                inBulan = 12;
            }

            hasilHari = hariK - hariH ;
            hasilBulan = (inBulan - iBulan) * 30;
            hasiltahun = (tahunK - tahunH) * 365;
            int totalwaktu = (hasilHari + hasilBulan + hasiltahun)/30;
            txLama.setText(String.valueOf(totalwaktu));
        }
    }//GEN-LAST:event_txttanggalkembaliPropertyChange

    private void txNonbungaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNonbungaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNonbungaKeyPressed

    private void txLamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txLamaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
            {
                int lama=Integer.parseInt(txLama.getText());
                if(lama>=37)
                {
                    JOptionPane.showMessageDialog(null,"Lama angsuran tidak boleh lebih dari 36 bulan");
                    txLama.setText("");
                    txLama.requestFocus();
                }
                else
                {
                    txBunga.requestFocus();
                }
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_txLamaKeyPressed

    private void txLamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txLamaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txLamaKeyTyped

    private void txTotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTotKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotKeyPressed

    private void txBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBungaActionPerformed

    private void txBungaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBungaKeyPressed
        int totpinjaman,nonbunga,angsuran;
        NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumIntegerDigits(0);
        numberFormat.setGroupingUsed(true);

        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            int pinjam=Integer.parseInt(txJmlPinjaman.getText());
            int bunga=Integer.parseInt(txBunga.getText());
            int lama=Integer.parseInt(txLama.getText());

            int bunga2=(bunga * pinjam) / 100;
            txBunga2.setText(String.valueOf(bunga2));

            nonbunga = pinjam / lama;
            txNonbunga.setText(String.valueOf(nonbunga));
            //            txNonbunga.setText(numberFormat.format(Double.parseDouble(txJmlPinjaman.getText())/Double.parseDouble(txLama.getText())));

            totpinjaman =  (pinjam + bunga2);
            txTot.setText(String.valueOf(totpinjaman));
            //            txTot.setText(Double.toString(Double.parseDouble(txJmlPinjaman.getText())+Double.parseDouble(txBunga2.getText())));

            angsuran =  (nonbunga + bunga2);
            txAngsuran.setText(String.valueOf(angsuran));

            txJmlPinjaman.setText(String.valueOf(pinjam));
            //            txAngsuran.setText(Double.toString(Double.parseDouble(txNonbunga.getText())+Double.parseDouble(txBunga2.getText())));
        }
    }//GEN-LAST:event_txBungaKeyPressed

    private void txBungaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBungaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txBungaKeyTyped

    private void txBunga2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBunga2KeyPressed

    }//GEN-LAST:event_txBunga2KeyPressed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        AksiTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        AksiEdit();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        AksiHapus(evt);
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        AksiSimpanEdit(evt);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        AksiKeluar(evt);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
        MouseClik(evt);
    }//GEN-LAST:event_tblPinjamMouseClicked

    private void txPinjBaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPinjBaruKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txPinjBaruKeyTyped

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        int sisa,baru,hasil;
        
        sisa = Integer.parseInt(txSisa.getText());
        baru = Integer.parseInt(txPinjBaru.getText());
        
        hasil = sisa + baru;
        
        txJmlPinjaman.setText(String.valueOf(hasil));
    }//GEN-LAST:event_bHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_PinjamanBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_PinjamanBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_PinjamanBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_PinjamanBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_PinjamanBaru dialog = new F_PinjamanBaru(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPinjam;
    private javax.swing.JTextField txAngsuran;
    private javax.swing.JTextField txBunga;
    private javax.swing.JTextField txBunga2;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txJmlPinjaman;
    private javax.swing.JTextField txKdPinjaman;
    private javax.swing.JTextField txLama;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNonbunga;
    private javax.swing.JTextField txPinjBaru;
    private javax.swing.JTextField txSisa;
    private javax.swing.JTextField txTot;
    private javax.swing.JButton txView;
    private com.toedter.calendar.JDateChooser txttanggalkembali;
    private com.toedter.calendar.JDateChooser txttglpinjam;
    // End of variables declaration//GEN-END:variables

    void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode");
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Tgl Pinjam");
        tbl.addColumn("Tgl Tempo");
        tbl.addColumn("Lama");
        tbl.addColumn("Bunga");
        tbl.addColumn("Jumlah Bunga");
        tbl.addColumn("Total Pinjam");
        tbl.addColumn("Non Bunga");
        tbl.addColumn("Angsuran"); 
        tblPinjam.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("Select * from t_pinjam");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getString("kd_pinjaman"),
                    res.getString("No_anggota"),
                    res.getString("Nama"),
                    res.getString("Jml_pinjam"),
                    res.getDate("Tgl_pinjam"),
                    res.getDate("Tgl_tempo"),
                    res.getString("Lama"),
                    res.getString("Bunga"),
                    res.getString("Jml_bunga"),
                    res.getString("Tot_pinjaman"),
                    res.getString("Non_bunga"),
                    res.getString("Angsuran"),
                });
                tblPinjam.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            tblPinjam.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblPinjam.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblPinjam.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblPinjam.getColumnModel().getColumn(3).setPreferredWidth(500);
            tblPinjam.getColumnModel().getColumn(3).setCellRenderer(kanan);
            tblPinjam.getColumnModel().getColumn(4).setPreferredWidth(400);
            tblPinjam.getColumnModel().getColumn(5).setPreferredWidth(400);
            tblPinjam.getColumnModel().getColumn(6).setPreferredWidth(200);
            tblPinjam.getColumnModel().getColumn(7).setPreferredWidth(200);
            tblPinjam.getColumnModel().getColumn(7).setCellRenderer(kanan);
            tblPinjam.getColumnModel().getColumn(8).setPreferredWidth(500);
            tblPinjam.getColumnModel().getColumn(8).setCellRenderer(kanan);
            tblPinjam.getColumnModel().getColumn(9).setPreferredWidth(500);
            tblPinjam.getColumnModel().getColumn(9).setCellRenderer(kanan);
            tblPinjam.getColumnModel().getColumn(10).setPreferredWidth(400);
            tblPinjam.getColumnModel().getColumn(10).setCellRenderer(kanan);
            tblPinjam.getColumnModel().getColumn(11).setPreferredWidth(400);
            tblPinjam.getColumnModel().getColumn(11).setCellRenderer(kanan);
    }
    
    void tombol(boolean a,boolean b){
        bTambah.setEnabled(a);
        bEdit.setEnabled(a);
        bHapus.setEnabled(a);
        bSimpan.setEnabled(b);
        bHitung.setEnabled(b);
    }
    
    void bersih(){
        //txKdPinjaman.setText("");
        txID.setText("");
        txNama.setText("");
        txttglpinjam.setDate(null);
        txttanggalkembali.setDate(null);
        txJmlPinjaman.setText("");
        txLama.setText("");
        txBunga.setText("");
        txBunga2.setText("");
        txNonbunga.setText("");
        txTot.setText("");
        txAngsuran.setText("");
    }
    
    void AturText(boolean atur){
        //txKdPinjaman.setEnabled(atur);
        txView.setEnabled(atur);
        txttglpinjam.setEnabled(atur);
        txttanggalkembali.setEnabled(atur);
        txPinjBaru.setEnabled(atur);
        txJmlPinjaman.setEnabled(atur);
        txLama.setEnabled(atur);
        txBunga.setEnabled(atur);
    }
    
    void AksiTambah(){
        SIMPANEDIT = "Add";
//        noUrut();
        ID();
        bersih();
        tombol(false, true);
        AturText(true);
        bKeluar.setText("BATAL");
        tblPinjam.setVisible(false);
    }
    
    void AksiEdit(){
        if(txKdPinjaman.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Rubah");
        }
        else{
            SIMPANEDIT = "Edit";
            tombol(false, true);
            AturText(true);
            bKeluar.setText("BATAL");
            tblPinjam.setVisible(false);
            //bPinjamBaru.setEnabled(true);
        }        
    }
    
    void AksiHapus(java.awt.event.ActionEvent evt){
        if(txKdPinjaman.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Hapus");
        }
        else{
            int selectedOption = JOptionPane.showConfirmDialog(null, "Yakin anda akan menghapus ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                try {
                    Statement statement=(Statement)Koneksi.GetConnection().createStatement();String sql = "DELETE FROM t_pinjam WHERE kd_pinjaman = '"+txKdPinjaman.getText()+"';";                    
                    statement.executeUpdate(sql);
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    bersih();
                    tombol(true, false);
                    txKdPinjaman.setText("");
                } catch (Exception DBException) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus " + DBException);
                    bersih();
                }
            }            
            tampil();
        }
    }
    
    void AksiKeluar(java.awt.event.ActionEvent evt){
        if(bKeluar.getText().equals("KELUAR")){
            dispose();
        }
        else{
            txKdPinjaman.setText("");
            AturText(false);
            bKeluar.setText("KELUAR");
            tombol(true, false);
            tblPinjam.setVisible(true);
//            bPinjamBaru.setEnabled(false);
            bersih();
        }
    }  
        
    public void itemTerpilih(){
        view_pinjamBaru fBR = new view_pinjamBaru(null, rootPaneCheckingEnabled);
        fBR.fBU = this;
        txID.setText(No_anggota);
        txNama.setText(Nama);
        txSisa.setText(Pinjam);
    }
    
    public void itemTerpilih1(){
        view_pinjamBaru fBR = new view_pinjamBaru(null, rootPaneCheckingEnabled);
        fBR.fBU = this;
        txID.setText(No_anggota);
        txNama.setText(Nama);
        txSisa.setText(Pinjam);
    }
    
    void AksiSimpanEdit(java.awt.event.ActionEvent evt){
        tblPinjam.setVisible(true);
        
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttglpinjam.getDate()));
        
        String tmp ="yyyy-MM-dd";
        SimpleDateFormat ft = new SimpleDateFormat(tmp);
        String tanggal1 = String.valueOf(ft.format(txttanggalkembali.getDate()));
                
        if (SIMPANEDIT.equalsIgnoreCase("Add")){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "INSERT INTO t_pinjam(kd_pinjaman, No_anggota,Nama,Jml_pinjam,Tgl_pinjam,Tgl_tempo,Lama,Bunga,Jml_bunga,Tot_pinjaman,Non_bunga,Angsuran) "
                        + "VALUES ('"+txKdPinjaman.getText()+"','"+txID.getText()+"','"+txNama.getText()+"','"+txJmlPinjaman.getText()+"','"+tanggal+"','"+tanggal1+"',"
                        + "'"+txLama.getText()+"','"+txBunga.getText()+"','"+txBunga2.getText()+"',"
                        + "'"+txTot.getText()+"','"+txNonbunga.getText()+"','"+txAngsuran.getText()+"')";
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                txKdPinjaman.setText("");
                bersih();
                AturText(false);
                tombol(true, false);
                bKeluar.setText("KELUAR");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }
        }
        else{
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "UPDATE t_pinjam SET No_anggota = '" +txID.getText()+"',"
                        + "Nama = '" + txNama.getText()+"',"
                        + "Jml_pinjam = '" + txJmlPinjaman.getText()+"',"
                        + "Tgl_pinjam = '" + tanggal +"',"
                        + "Tgl_tempo = '" + tanggal1 +"',"
                        + "Lama = '" + txLama.getText()+"',"
                        + "Bunga = '" + txBunga.getText()+"',"
                        + "Jml_bunga = '" + txBunga2.getText()+"',"
                        + "Tot_pinjaman = '" + txTot.getText()+"',"
                        + "Non_bunga = '" + txNonbunga.getText()+"',"
                        + "Angsuran = '" + txAngsuran.getText()+"'"
                        + "WHERE kd_pinjaman = '"+txKdPinjaman.getText()+"'";                    
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Rubah");
                bersih();
                AturText(false);
                tombol(true, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Rubah" + e);
            }
        }
    }
    
    void MouseClik(java.awt.event.MouseEvent evt){
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            int row = tblPinjam.rowAtPoint(evt.getPoint());

            String kd_pinjaman = tblPinjam.getValueAt(row, 0).toString();
            String No_Anggota = tblPinjam.getValueAt(row, 1).toString();
            String Nama = tblPinjam.getValueAt(row, 2).toString();
            String Jml_pinjam = tblPinjam.getValueAt(row, 3).toString();
            String Tgl_pinjam = tblPinjam.getValueAt(row, 4).toString();
            String Tgl_tempo = tblPinjam.getValueAt(row, 5).toString();
            String Lama = tblPinjam.getValueAt(row, 6).toString();
            String Bunga = tblPinjam.getValueAt(row, 7).toString();
            String Jml_bunga = tblPinjam.getValueAt(row, 8).toString();
            String Tot_pinjaman = tblPinjam.getValueAt(row, 9).toString();
            String Non_bunga = tblPinjam.getValueAt(row, 10).toString();
            String Angsuran = tblPinjam.getValueAt(row, 11).toString();
                        
            txKdPinjaman.setText(String.valueOf(kd_pinjaman));
            txID.setText(String.valueOf(No_Anggota));
            txNama.setText(String.valueOf(Nama));
            txJmlPinjaman.setText(String.valueOf(Jml_pinjam));
            txttglpinjam.setDate(java.sql.Date.valueOf(Tgl_pinjam));
            txttanggalkembali.setDate(java.sql.Date.valueOf(Tgl_tempo));
            txLama.setText(String.valueOf(Lama));
            txBunga.setText(String.valueOf(Bunga));
            txBunga2.setText(String.valueOf(Jml_bunga));
            txTot.setText(String.valueOf(Tot_pinjaman));
            txNonbunga.setText(String.valueOf(Non_bunga));
            txAngsuran.setText(String.valueOf(Angsuran));
            } catch (Exception e) {
        }        
    }
    
    private void noUrut(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql ="SELECT MAX(right(kd_pinjaman,1)) AS no FROM t_pinjam";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first()==false){
                txKdPinjaman.setText("PJ-1");
            }
            else{
                rs.last();
                int no=rs.getInt(1)+1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i = 0; i < 2-pjg_cno; i++) {
                    cno=""+cno;
                }
                txKdPinjaman.setText("PJ-"+ cno);
            }
        } catch (Exception e) {
            System.err.println("Error = "+ e);
        }
    }
    
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
        }
    }
    void format(){
        NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumIntegerDigits(0);
        numberFormat.setGroupingUsed(true);
        
        int pinjam=Integer.parseInt(txJmlPinjaman.getText());
        txJmlPinjaman.setText(numberFormat.format(pinjam));
    }
    
    void ID(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql = "SELECT MAX(right(kd_pinjaman,5)) AS no FROM t_pinjam";
            ResultSet rs = statement.executeQuery(sql);
            
            while(rs.next())
            {
                if(rs.first() == false)
                {
                txKdPinjaman.setText("PJ-000001");
            }
                else
            {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<6-noLong;a++)
                    { 
                        no = "0" + no;
                    }
                   txKdPinjaman.setText("PJ-" + no);
                 }        
            }
       rs.close();
        } catch (Exception e) {
        }
    }
}
