package Form;

import Database.Koneksi;
import Database.Koneksi2;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class F_SHU extends javax.swing.JDialog {

    public TableCellRenderer kanan = new RenderingKanan();
    public TableCellRenderer tengah = new RenderingTengah();
    String SIMPANEDIT;
    
    private DefaultTableModel model;
    //String TglAwal1,TglAkhir1,TglAwal2,TglAkhir2,TglAwal3,TglAkhir3;
    
    public F_SHU(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Saham();
        Tgl1(false, true);
        tampil();
        bersih();
        tombol(true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lAnggota = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txPropisi = new javax.swing.JTextField();
        txTHR = new javax.swing.JTextField();
        txSimPokok = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lTotalSHU = new javax.swing.JLabel();
        TxAwal1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        TxAkhir1 = new com.toedter.calendar.JDateChooser();
        rdTgl1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txPengurus = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txPengurus1 = new javax.swing.JTextField();
        txCadangan = new javax.swing.JTextField();
        txCadangan1 = new javax.swing.JTextField();
        txDana = new javax.swing.JTextField();
        txDana1 = new javax.swing.JTextField();
        txDoor = new javax.swing.JTextField();
        txDoor1 = new javax.swing.JTextField();
        txAnggota = new javax.swing.JTextField();
        txAnggota1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txSembako = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txSembako1 = new javax.swing.JTextField();
        lTotalSHU1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPinjam1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSHU = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lAnggota.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lAnggota.setText("0");
        jPanel3.add(lAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel12.setText("Simpanan Pokok");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel13.setText("THR");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel15.setText("Dana Propisi");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, -1));

        txPropisi.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel3.add(txPropisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, -1));

        txTHR.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel3.add(txTHR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, -1));

        txSimPokok.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel3.add(txSimPokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setText("Data");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lTotalSHU.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lTotalSHU.setText("0");
        jPanel3.add(lTotalSHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 310, 160));
        getContentPane().add(TxAwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 133, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setText("s/d");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        getContentPane().add(TxAkhir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 133, -1));

        buttonGroup1.add(rdTgl1);
        rdTgl1.setText("Seleksi Berdasarkan Tanggal");
        rdTgl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTgl1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdTgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Hitung SHU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 114, -1));

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembagian SHU"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel19.setText("Dana Sosial");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel20.setText("Anggota");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel21.setText("Doorprize");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txPengurus.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txPengurus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPengurusKeyTyped(evt);
            }
        });
        jPanel5.add(txPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 40, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel23.setText("Total SHU");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel24.setText("Pengurus");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel25.setText("Cadangan");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txPengurus1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txPengurus1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPengurus1KeyTyped(evt);
            }
        });
        jPanel5.add(txPengurus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, -1));

        txCadangan.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txCadangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCadanganKeyTyped(evt);
            }
        });
        jPanel5.add(txCadangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 40, -1));

        txCadangan1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txCadangan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCadangan1KeyTyped(evt);
            }
        });
        jPanel5.add(txCadangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));

        txDana.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txDana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDanaKeyTyped(evt);
            }
        });
        jPanel5.add(txDana, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 40, -1));

        txDana1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txDana1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDana1KeyTyped(evt);
            }
        });
        jPanel5.add(txDana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, -1));

        txDoor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txDoor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDoorKeyTyped(evt);
            }
        });
        jPanel5.add(txDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, -1));

        txDoor1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txDoor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDoor1KeyTyped(evt);
            }
        });
        jPanel5.add(txDoor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        txAnggota.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAnggotaKeyTyped(evt);
            }
        });
        jPanel5.add(txAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 40, -1));

        txAnggota1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txAnggota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAnggota1KeyTyped(evt);
            }
        });
        jPanel5.add(txAnggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, -1));

        jLabel1.setText("%");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel2.setText("%");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel3.setText("%");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel4.setText("%");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel8.setText("%");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        txSembako.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txSembako.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSembakoKeyTyped(evt);
            }
        });
        jPanel5.add(txSembako, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 40, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel22.setText("Dana Sembako");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel9.setText("%");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        txSembako1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txSembako1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSembako1KeyTyped(evt);
            }
        });
        jPanel5.add(txSembako1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));

        lTotalSHU1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lTotalSHU1.setText("0");
        jPanel5.add(lTotalSHU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 340, 250));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Data SHU"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblPinjam1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblPinjam1);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 140));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 170));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pembagian Hasil Usaha"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tSHU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tSHU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSHUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tSHU);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 860, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 880, 170));

        bTambah.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        bHapus.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        bSimpan.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        bKeluar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bKeluar.setText("KELUAR");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, -1, -1));

        setSize(new java.awt.Dimension(921, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        new F_BagiSHU(null, rootPaneCheckingEnabled).show();
        HitungSHU();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdTgl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTgl1ActionPerformed
        Tgl1(true, false);
    }//GEN-LAST:event_rdTgl1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        /*        if(rdSemua1.isSelected()){
            //Jumlah Simpanan Pokok & Adm
            try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT Count(NO_ANGGOTA),NAMA,SUM(Sim_pokok),SUM(THR),SUM(BUNGA), COALESCE(Sim_pokok+Adm+THR+BUNGA,0)AS 'SUM(GRAND TOTAL)' FROM (\n" +
"	SELECT \n" +
"    	A0.NO_ANGGOTA,\n" +
"    	A0.NAMA,\n" +
"    	A0.SIM_POKOK,\n" +
"    	A0.ADM,\n" +
"		SUM(COALESCE(B0.THR,0))AS 'THR',\n" +
"    	COALESCE(C0.JML_BUNGA,0)AS 'BUNGA'\n" +
"		\n" +
"    	FROM KOPERASI.t_anggota A0\n" +
"		LEFT JOIN KOPERASI.t_simpan B0 ON B0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"		LEFT JOIN KOPERASI.t_pinjam C0 ON C0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"		GROUP BY A0.NO_ANGGOTA)A");
            if (res.next()){
                String Pokok=res.getString("SUM(Sim_pokok)");
                String THR=res.getString("SUM(THR)");
                String Bunga=res.getString("SUM(Bunga)");
                String Data=res.getString("Count(NO_ANGGOTA)");
                    
                txSimPokok.setText(Pokok);
                txTHR.setText(THR);
                txPropisi.setText(Bunga);
                lAnggota.setText(Data);
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }                      
        }*/
        
        if(rdTgl1.isSelected()){
            //java.sql.Date Awal1 = new java.sql.Date(TxAwal1.getDate().getTime());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String TglAwal1 = sdf.format(TxAwal1.getDate().getTime());

            SimpleDateFormat ddf = new SimpleDateFormat("yyyy-MM-dd");
            String TglAkhir1 = ddf.format(TxAkhir1.getDate().getTime());
        
            try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT Count(NO_ANGGOTA),NAMA,SUM(Sim_pokok),SUM(THR),SUM(BUNGA), COALESCE(Sim_pokok+Adm+THR+BUNGA,0)AS 'SUM(GRAND TOTAL)' FROM (\n" +
"	SELECT \n" +
"    	A0.NO_ANGGOTA,\n" +
"    	A0.NAMA,\n" +
"    	A0.SIM_POKOK,\n" +
"    	A0.ADM,\n" +
"		SUM(COALESCE(B0.THR,0))AS 'THR',\n" +
"    	COALESCE(C0.JML_BUNGA,0)AS 'BUNGA'\n" +
"		\n" +
"    	FROM KOPERASI.t_anggota A0\n" +
"		LEFT JOIN KOPERASI.t_simpan B0 ON B0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"		LEFT JOIN KOPERASI.t_pinjam C0 ON C0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"\n" +
"	WHERE A0.Tgl_masuk BETWEEN '" + TglAwal1 +"' and '" + TglAkhir1 +"' "
                    + "GROUP BY A0.NO_ANGGOTA)A");
            
            if (res.next()){
                String Pokok=res.getString("SUM(Sim_pokok)");
                String THR=res.getString("SUM(THR)");
                String Bunga=res.getString("SUM(Bunga)");
                String Data=res.getString("Count(NO_ANGGOTA)");
                    
                txSimPokok.setText(Pokok);
                txTHR.setText(THR);
                txPropisi.setText(Bunga);
                lAnggota.setText(Data);
                
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
        
        proses();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txPengurusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPengurusKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txPengurusKeyTyped

    private void txCadanganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCadanganKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txCadanganKeyTyped

    private void txDanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDanaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txDanaKeyTyped

    private void txDoorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDoorKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txDoorKeyTyped

    private void txAnggotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAnggotaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txAnggotaKeyTyped

    private void txSembakoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSembakoKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txSembakoKeyTyped

    private void txPengurus1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPengurus1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txPengurus1KeyTyped

    private void txCadangan1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCadangan1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txCadangan1KeyTyped

    private void txDana1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDana1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txDana1KeyTyped

    private void txDoor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDoor1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txDoor1KeyTyped

    private void txAnggota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAnggota1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txAnggota1KeyTyped

    private void txSembako1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSembako1KeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txSembako1KeyTyped

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        AksiTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        AksiHapus(evt);
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        AksiSimpanEdit(evt);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        AksiKeluar(evt);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tSHUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSHUMouseClicked
        MouseClik(evt);
    }//GEN-LAST:event_tSHUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_SHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_SHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_SHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_SHU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_SHU dialog = new F_SHU(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TxAkhir1;
    private com.toedter.calendar.JDateChooser TxAwal1;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lAnggota;
    private javax.swing.JLabel lTotalSHU;
    private javax.swing.JLabel lTotalSHU1;
    private javax.swing.JRadioButton rdTgl1;
    private javax.swing.JTable tSHU;
    private javax.swing.JTable tblPinjam1;
    private javax.swing.JTextField txAnggota;
    private javax.swing.JTextField txAnggota1;
    private javax.swing.JTextField txCadangan;
    private javax.swing.JTextField txCadangan1;
    private javax.swing.JTextField txDana;
    private javax.swing.JTextField txDana1;
    private javax.swing.JTextField txDoor;
    private javax.swing.JTextField txDoor1;
    private javax.swing.JTextField txPengurus;
    private javax.swing.JTextField txPengurus1;
    private javax.swing.JTextField txPropisi;
    private javax.swing.JTextField txSembako;
    private javax.swing.JTextField txSembako1;
    private javax.swing.JTextField txSimPokok;
    private javax.swing.JTextField txTHR;
    // End of variables declaration//GEN-END:variables

    
    void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Periode 1");
        tbl.addColumn("Periode 2");
        tbl.addColumn("Banyak Data");
        tbl.addColumn("Total SHU");
        /*tbl.addColumn("%");
        tbl.addColumn("Pengurus1");
        tbl.addColumn("%");
        tbl.addColumn("Cadangan1");
        tbl.addColumn("%");
        tbl.addColumn("Sosial1");
        tbl.addColumn("%");
        tbl.addColumn("Doorprize1");
        tbl.addColumn("%"); 
        tbl.addColumn("Anggota1"); 
        tbl.addColumn("%"); 
        tbl.addColumn("Sembako1"); */
        tSHU.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("Select * from t_SHU");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getDate("Periode1"),
                    res.getDate("Periode2"),
                    res.getString("Data"),
                    res.getString("TotalSHU"),
                    res.getString("Pengurus"),
                    res.getString("Pengurus1"),
                    res.getString("Cadangan"),
                    res.getString("Cadangan1"),
                    res.getString("Sosial"),
                    res.getString("Sosial1"),
                    res.getString("Doorprize"),
                    res.getString("Doorprize1"),
                    res.getString("Anggota"),
                    res.getString("Anggota1"), 
                    res.getString("Sembako"),
                    res.getString("Sembako1"), 
                });
                tSHU.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            tSHU.getColumnModel().getColumn(0).setPreferredWidth(50);
            tSHU.getColumnModel().getColumn(1).setPreferredWidth(50);
            tSHU.getColumnModel().getColumn(2).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(3).setPreferredWidth(100);
            /*tSHU.getColumnModel().getColumn(4).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(5).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(5).setCellRenderer( kanan );
            tSHU.getColumnModel().getColumn(6).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(6).setCellRenderer( kanan );
            tSHU.getColumnModel().getColumn(7).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(8).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(9).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(10).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(11).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(12).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(13).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(14).setPreferredWidth(100);
            tSHU.getColumnModel().getColumn(15).setPreferredWidth(100);*/
    }
    
    void bersih(){
        TxAwal1.setDate(null);
        TxAkhir1.setDate(null);
        lAnggota.setText("");
        txSimPokok.setText("");
        txTHR.setText("");
        txPropisi.setText("");
        lTotalSHU.setText("");
        lTotalSHU1.setText("");
        txAnggota.setText("");
        txAnggota1.setText("");
        txCadangan.setText("");
        txCadangan1.setText("");
        txDana.setText("");
        txDana1.setText("");
        txDoor.setText("");
        txDoor1.setText("");
        txPengurus.setText("");
        txPengurus1.setText("");
        txSembako.setText("");
        txSembako1.setText("");
    }
    
    void tombol(boolean a,boolean b){
        bTambah.setEnabled(a);
//        bEdit.setEnabled(a);
        bHapus.setEnabled(a);
        bSimpan.setEnabled(b);
    }
    void AturText(boolean atur){
//        
    }
    
    void AksiSimpanEdit(java.awt.event.ActionEvent evt){
//        tblAnggota.setVisible(true);
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String Tgl1 = String.valueOf(fm.format(TxAwal1.getDate()));
        
        String tmpl ="yyyy-MM-dd";
        SimpleDateFormat fn = new SimpleDateFormat(tmpl);
        String Tgl2 = String.valueOf(fn.format(TxAkhir1.getDate()));
        
        if (SIMPANEDIT.equalsIgnoreCase("Add")){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "INSERT INTO t_SHU "
                        + "VALUES ('"+Tgl1+"','"+Tgl2+"','"+lAnggota.getText()+"',"
                        + "'"+lTotalSHU1.getText()+"','"+txPengurus.getText()+"','"+txPengurus1.getText()+"','"+txCadangan.getText()+"','"+txCadangan1.getText()+"',"
                        + "'"+txDana.getText()+"','"+txDana1.getText()+"','"+txDoor.getText()+"','"+txDoor1.getText()+"','"+txAnggota.getText()+"','"+txAnggota1.getText()+"',"
                        + "'"+txSembako.getText()+"','"+txSembako1.getText()+"')";
                statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                cetak();
                tampil();
                bersih();
                AturText(false);
                tombol(true, false);
                bKeluar.setText("KELUAR");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }
        }
        /*else{
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "UPDATE t_anggota SET Nama = '" +txNama.getText()+"',"
                        + "Alamat = '" + txAlamat.getText()+"',"
                        + "Tmp_lahir = '" + txTmpL.getText()+"',"
                        + "Tgl_lahir = '" + tanggal+"',"
                        + "Sim_pokok = '" + txsimpokok.getText()+"',"
                        + "Adm = '" + txAdm.getText()+"',"
                        + "No_telp = '" + txTelp.getText()+"',"
                        + "Pekerjaan = '" + cmbPekerjaan.getSelectedItem()+"',"
                        + "Tgl_masuk = '" + tglmasuk+"'"
                        + "WHERE No_anggota = '"+txID.getText()+"'";                    
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Rubah");
                bersih();
                AturText(false);
                tombol(true, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Rubah" + e);
            }
        }*/
    }
    
    void MouseClik(java.awt.event.MouseEvent evt){
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            int row = tSHU.rowAtPoint(evt.getPoint());

            String Periode1 = tSHU.getValueAt(row, 0).toString();
            String Periode2 = tSHU.getValueAt(row, 1).toString();
            String Data = tSHU.getValueAt(row, 2).toString();
            String TotalSHU = tSHU.getValueAt(row, 3).toString();
           
            TxAwal1.setDate(java.sql.Date.valueOf(Periode1));
            TxAkhir1.setDate(java.sql.Date.valueOf(Periode2));
            lAnggota.setText(String.valueOf(Data));
            lTotalSHU.setText(String.valueOf(TotalSHU));
            } catch (Exception e) {
        }        
    }
    void AksiHapus(java.awt.event.ActionEvent evt){
        if(lAnggota.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Hapus");
        }
        else{
            int selectedOption = JOptionPane.showConfirmDialog(null, "Yakin anda akan menghapus ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                try {
                    Statement statement=(Statement)Koneksi.GetConnection().createStatement();

                    String sql = "DELETE FROM t_SHU WHERE Data= '"+lAnggota.getText()+"';";                    
                    statement.executeUpdate(sql);
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    bersih();
                    tombol(true, false);
                } catch (Exception DBException) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus " + DBException);
                    bersih();
                }
            }            
            tampil();
        }
    }
    
    void AksiKeluar(java.awt.event.ActionEvent evt){
        if(bKeluar.getText().equals("KELUAR")){
            dispose();
        }
        else{
            txAnggota.setText("");
            AturText(false);
            bKeluar.setText("KELUAR");
            tombol(true, false);
            tSHU.setVisible(true);
            bersih();
        }
    }
    void AksiTambah(){
        SIMPANEDIT = "Add";
        //buatnomor();
//        noUrut();
        //auto();
//        ID();
        //oto();
        bersih();
        tombol(false, true);
        AturText(true);
        bKeluar.setText("BATAL");
        tSHU.setVisible(false);
    }
    
    /*void AksiEdit(){
        if(txID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Rubah");
        }
        else{
            SIMPANEDIT = "Edit";
            tombol(false, true);
            AturText(true);
            bKeluar.setText("BATAL");
            tblAnggota.setVisible(false);
        }        
    }*/
    
    void Saham(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No. Anggota");
        tbl.addColumn("Nama");
        tbl.addColumn("Tanggal");
        tbl.addColumn("Simpanan");
        tbl.addColumn("THR");
        tbl.addColumn("Bunga");
        tbl.addColumn("GRAND TOTAL");
        tblPinjam1.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT NO_ANGGOTA,NAMA,Tgl_masuk,Sim_pokok,THR,Jml_bunga, COALESCE(Sim_pokok+THR+Jml_bunga,0)AS 'GRAND TOTAL' FROM (\n" +
"	SELECT\n" +
"    	A0.NO_ANGGOTA,\n" +
"    	A0.NAMA,\n" +
"    	A0.Tgl_masuk,\n" +
"    	A0.SIM_POKOK,\n" +
"    	SUM(COALESCE(B0.THR,0))AS 'THR',\n" +
"    	COALESCE(C0.JML_BUNGA,0)AS 'JML_BUNGA'\n" +
"    	FROM KOPERASI.t_anggota A0\n" +
"		LEFT JOIN KOPERASI.t_simpan B0 ON B0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"		LEFT JOIN KOPERASI.t_pinjam C0 ON C0.NO_ANGGOTA=A0.NO_ANGGOTA\n" +
"		GROUP BY A0.NO_ANGGOTA)A");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getString("No_anggota"),
                    res.getString("Nama"),
                    res.getDate("Tgl_masuk"),
                    res.getString("Sim_pokok"),
                    res.getString("THR"),
                    res.getString("Jml_bunga"),
                    res.getString("GRAND TOTAL"),
                });
                tblPinjam1.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            tblPinjam1.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblPinjam1.getColumnModel().getColumn(0).setCellRenderer( tengah );
            tblPinjam1.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblPinjam1.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblPinjam1.getColumnModel().getColumn(2).setCellRenderer( tengah );
            tblPinjam1.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblPinjam1.getColumnModel().getColumn(3).setCellRenderer( kanan );
            tblPinjam1.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblPinjam1.getColumnModel().getColumn(4).setCellRenderer( kanan );
            tblPinjam1.getColumnModel().getColumn(5).setPreferredWidth(200);
            tblPinjam1.getColumnModel().getColumn(5).setCellRenderer( kanan );
            tblPinjam1.getColumnModel().getColumn(6).setPreferredWidth(200);
            tblPinjam1.getColumnModel().getColumn(6).setCellRenderer( kanan );
    }
    void Tgl1(boolean a, boolean b){
        TxAwal1.setEnabled(a);
        TxAkhir1.setEnabled(a);
        
        
    }
    
    
    void proses(){
        int pokok,adm,thr,Propisi,totalSHU;
        
        NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumIntegerDigits(0);
        numberFormat.setGroupingUsed(true);
        
        pokok = Integer.parseInt(txSimPokok.getText());
        thr = Integer.parseInt(txTHR.getText());
        Propisi = Integer.parseInt(txPropisi.getText());
        
        totalSHU = pokok  + thr + Propisi;
        
        lTotalSHU.setText(String.valueOf(totalSHU));
        lTotalSHU1.setText(numberFormat.format(totalSHU));
    }
    
    void HitungSHU(){
        int totalSHU,totalSHU1;
        double pengurus, cadangan, dana, door, anggota, sembako;
        double pengurus1, cadangan1, dana1, door1, anggota1, sembako1;

        NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumIntegerDigits(0);
        numberFormat.setGroupingUsed(true);
        
        totalSHU = Integer.parseInt(lTotalSHU.getText());
        
        pengurus = Double.parseDouble(txPengurus.getText());
        cadangan = Double.parseDouble(txCadangan.getText());
        dana = Double.parseDouble(txDana.getText());
        door = Double.parseDouble(txDoor.getText());
        anggota = Double.parseDouble(txAnggota.getText());
        sembako = Double.parseDouble(txSembako.getText());
        
        pengurus1 = (totalSHU * pengurus) / 100;
        txPengurus1.setText(numberFormat.format(pengurus1));
        
        cadangan1 = (totalSHU * cadangan) / 100;
        txCadangan1.setText(numberFormat.format(cadangan1));
        
        dana1 = (totalSHU * dana) / 100;
        txDana1.setText(numberFormat.format(dana1));
        
        door1 = (totalSHU * door) / 100;
        txDoor1.setText(numberFormat.format(door1));
        
        anggota1 = (totalSHU * anggota) / 100;
        txAnggota1.setText(numberFormat.format(anggota1));
        
        sembako1 = (totalSHU * sembako) / 100;
        txSembako1.setText(numberFormat.format(sembako1));
        
//        totalSHU1 = (int) (pengurus1 + cadangan1 + door1 + dana1 + anggota1 + sembako1);
        
    }
    
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
        }
    }
    
    void cetak(){
        try {
                   String path = System.getProperty ("user.dir") +"/src/Report/LapSHU.jasper";
                  //  File file=new File("src/nyobarepotlagi/report1.jrxml");
                  //  JasperDesign jasperdesign=JRXmlLoader.load(file);
                    HashMap parameter = new HashMap();
                    //parameter.put("Kd_Angsur", txKdAngsuran.getText());
                   // JasperReport jasperreport=JasperCompileManager.compileReport(jasperdesign);
                    JasperPrint print = JasperFillManager.fillReport(path, parameter, Koneksi2.getkoneksi());
                    JasperViewer.viewReport(print, false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
            }
    }
}
