package Form;

import Database.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author GHITEEN
 */
public class F_Simpanan extends javax.swing.JDialog {
    public TableCellRenderer kanan = new RenderingKanan();
    public TableCellRenderer tengah = new RenderingTengah();
    
    public String No_anggota, Nama;
    
    //Deklarasi Get
    public String getNo_anggota() {
        return No_anggota;
    }

    public String getNama() {
        return Nama;
    }
    //
    private String hasil;
    private int c,b;
    
    private DefaultTableModel model;
    String SIMPANEDIT;
    
    public F_Simpanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tampil();
        bersih();
        tombol(true, false);
        AturText(false);
        //noUrut();
        TotalSaldo();
        //Saldo();
        
        txKdSimpanan.setEnabled(false);
        txID.setEnabled(false);
        txSaldo.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txKdSimpanan = new javax.swing.JTextField();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        TxTglSim = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        bAnggota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txSaldo = new javax.swing.JTextField();
        txThr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Simpanan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rdID = new javax.swing.JRadioButton();
        rdNama = new javax.swing.JRadioButton();
        txCari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LNamaCek = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lCeksaldo = new javax.swing.JLabel();
        LTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setText("No Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Nama Anggota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setText("Kode Simpanan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Simpanan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txKdSimpanan.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel1.add(txKdSimpanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 250, -1));

        txID.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });
        txID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txIDPropertyChange(evt);
            }
        });
        txID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txIDKeyReleased(evt);
            }
        });
        jPanel1.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, -1));

        txNama.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txNamaKeyReleased(evt);
            }
        });
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, -1));
        jPanel1.add(TxTglSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, -1));

        jButton6.setText("...");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 30, -1));

        bAnggota.setText("...");
        bAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(bAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel8.setText("Saldo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txSaldo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jPanel2.add(txSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, -1));

        txThr.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txThr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txThrKeyTyped(evt);
            }
        });
        jPanel2.add(txThr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setText("Setoran");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Simpanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Simpanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SimpananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Simpanan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 780, 270));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bEdit.setText("EDIT");
        bEdit.setPreferredSize(new java.awt.Dimension(75, 23));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel4.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 40));

        bHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.setPreferredSize(new java.awt.Dimension(75, 23));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel4.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 40));

        bSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.setPreferredSize(new java.awt.Dimension(75, 23));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 40));

        bKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bKeluar.setText("KELUAR");
        bKeluar.setPreferredSize(new java.awt.Dimension(75, 23));
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel4.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 40));

        bTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bTambah.setText("TAMBAH");
        bTambah.setPreferredSize(new java.awt.Dimension(75, 23));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel4.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Cari :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(rdID);
        rdID.setText("ID");
        rdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdIDActionPerformed(evt);
            }
        });
        rdID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdIDKeyReleased(evt);
            }
        });
        jPanel5.add(rdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        buttonGroup1.add(rdNama);
        rdNama.setText("Nama");
        jPanel5.add(rdNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txCari.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txCariKeyReleased(evt);
            }
        });
        jPanel5.add(txCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel9.setText("Total Saldo");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel7.setText("Total Saldo");

        LNamaCek.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        LNamaCek.setForeground(new java.awt.Color(204, 0, 0));
        LNamaCek.setText("<Nama>");

        jButton1.setText("Cek Saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lCeksaldo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lCeksaldo.setText("0");

        LTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LTotal.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LNamaCek)
                                            .addComponent(lCeksaldo))
                                        .addGap(137, 137, 137)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LTotal)
                                            .addComponent(jLabel7))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(LNamaCek)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LTotal)
                            .addComponent(lCeksaldo)
                            .addComponent(jLabel5)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(224, 224, 224)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(832, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnggotaActionPerformed
        view_ang_simpan fS = new view_ang_simpan(null, rootPaneCheckingEnabled);
        fS.fAS = this;
        fS.setVisible(true);
    }//GEN-LAST:event_bAnggotaActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        AksiEdit();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        AksiHapus(evt);
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        AksiSimpanEdit(evt);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        AksiKeluar(evt);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tbl_SimpananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SimpananMouseClicked
        MouseClik(evt);
    }//GEN-LAST:event_tbl_SimpananMouseClicked

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        AksiTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        
    }//GEN-LAST:event_txIDActionPerformed

    private void txIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txIDPropertyChange
        
    }//GEN-LAST:event_txIDPropertyChange

    private void txCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCariKeyReleased
        LNamaCek.setText(txCari.getText());
        if (rdID.isSelected()){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode");
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Tgl Simpan");
            tbl.addColumn("THR");
            tbl.addColumn("Saldo");
            //tbl.addColumn("Total"); 
            tbl_Simpanan.setModel(tbl);
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT * FROM t_simpan WHERE No_anggota LIKE '"+txCari.getText()+"%'");
                while (res.next()) 
                {
                    tbl.addRow(new Object[]{
                        res.getString("kd_simpanan"),
                        res.getString("No_anggota"),
                        res.getString("Nama"),
                        res.getDate("Tgl_simpanan"),
                        res.getString("THR"),
                        res.getString("Saldo"),
                        //res.getString("Tot_saldo"),
                    });
                    tbl_Simpanan.setModel(tbl);
                    //Saldo();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
        if (rdNama.isSelected()){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode");
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Tgl Simpan");
            tbl.addColumn("THR");
            tbl.addColumn("Saldo");
            //tbl.addColumn("Total"); 
            tbl_Simpanan.setModel(tbl);
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT * FROM t_simpan WHERE Nama LIKE '"+txCari.getText()+"%'");
                while (res.next()) 
                {
                    tbl.addRow(new Object[]{
                        res.getString("kd_simpanan"),
                        res.getString("No_anggota"),
                        res.getString("Nama"),
                        res.getDate("Tgl_simpanan"),
                        res.getString("THR"),
                        res.getString("Saldo"),
                        //res.getString("Tot_saldo"),
                    });
                    tbl_Simpanan.setModel(tbl);
                    //Saldo();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
    }//GEN-LAST:event_txCariKeyReleased

    private void txIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIDKeyReleased
        
    }//GEN-LAST:event_txIDKeyReleased

    private void txNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNamaKeyReleased
        /*DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode");
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Tgl Simpan");
            tbl.addColumn("THR");
            tbl.addColumn("Saldo");
            //tbl.addColumn("Total"); 
            tbl_Simpanan.setModel(tbl);
        */    try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT SUM(THR) FROM t_simpan WHERE Nama LIKE '"+txNama.getText()+"%'");
                while (res.next()){
                    
                    String THR=res.getString("SUM(THR)");
                    txSaldo.setText(THR);
                    /*while (res.next()) 
                    {
                        tbl.addRow(new Object[]{
                            res.getString("kd_simpanan"),
                            res.getString("No_anggota"),
                            res.getString("Nama"),
                            res.getDate("Tgl_simpanan"),
                            res.getString("THR"),
                            res.getString("Saldo"),
                        });
                        tbl_Simpanan.setModel(tbl);

                    }*/
                    
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
    }//GEN-LAST:event_txNamaKeyReleased

    private void rdIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdIDKeyReleased
        
    }//GEN-LAST:event_rdIDKeyReleased

    private void rdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdIDActionPerformed
        
            
        
    }//GEN-LAST:event_rdIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (rdID.isSelected()){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT SUM(THR) FROM t_simpan WHERE No_anggota LIKE '"+LNamaCek.getText()+"%'");
                if (res.next()){
                    String THR=res.getString("SUM(THR)");
                    lCeksaldo.setText(THR);
                    }    
                if (LNamaCek.getText().isEmpty()){
                    lCeksaldo.setText("0");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
        else {
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                ResultSet res=statement.executeQuery("SELECT SUM(THR) FROM t_simpan WHERE Nama LIKE '"+LNamaCek.getText()+"%'");
                if (res.next()){
                    String THR=res.getString("SUM(THR)");
                    lCeksaldo.setText(THR);
                    }    
                if (LNamaCek.getText().isEmpty()){
                    lCeksaldo.setText("0");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txThrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txThrKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txThrKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Simpanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Simpanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Simpanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Simpanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_Simpanan dialog = new F_Simpanan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNamaCek;
    private javax.swing.JLabel LTotal;
    private com.toedter.calendar.JDateChooser TxTglSim;
    private javax.swing.JButton bAnggota;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCeksaldo;
    private javax.swing.JRadioButton rdID;
    private javax.swing.JRadioButton rdNama;
    private javax.swing.JTable tbl_Simpanan;
    private javax.swing.JTextField txCari;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txKdSimpanan;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txSaldo;
    private javax.swing.JTextField txThr;
    // End of variables declaration//GEN-END:variables

    void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode");
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("Tgl Simpan");
        tbl.addColumn("THR");
        tbl.addColumn("Saldo");
        //tbl.addColumn("Total"); 
        tbl_Simpanan.setModel(tbl);
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("Select * from t_simpan");
            while (res.next()) 
            {
                tbl.addRow(new Object[]{
                    res.getString("kd_simpanan"),
                    res.getString("No_anggota"),
                    res.getString("Nama"),
                    res.getDate("Tgl_simpanan"),
                    res.getString("THR"),
                    res.getString("Saldo"),
                    //res.getString("Tot_saldo"),
                });
                tbl_Simpanan.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah" +e);
        }
            tbl_Simpanan.getColumnModel().getColumn(0).setPreferredWidth(300);
            tbl_Simpanan.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbl_Simpanan.getColumnModel().getColumn(2).setPreferredWidth(500);
            tbl_Simpanan.getColumnModel().getColumn(3).setPreferredWidth(500);
            tbl_Simpanan.getColumnModel().getColumn(4).setPreferredWidth(400);
            tbl_Simpanan.getColumnModel().getColumn(4).setCellRenderer(kanan);
            tbl_Simpanan.getColumnModel().getColumn(5).setPreferredWidth(400);
            tbl_Simpanan.getColumnModel().getColumn(5).setCellRenderer(kanan);
            //tbl_Simpanan.getColumnModel().getColumn(6).setPreferredWidth(200);
    }
    
    void tombol(boolean a,boolean b){
        bTambah.setEnabled(a);
        bEdit.setEnabled(a);
        bHapus.setEnabled(a);
        bSimpan.setEnabled(b);
    }
    
    void bersih(){
        //txKdSimpanan.setText("");
        txID.setText("");
        txNama.setText("");
        txThr.setText("0");
        txSaldo.setText("0");
        //txTotSaldo.setText("");
    }
    
    void AturText(boolean atur){
        txNama.setEnabled(atur);
        TxTglSim.setEnabled(atur);
        TxTglSim.setDate(null);
        txThr.setEnabled(atur);
        bAnggota.setEnabled(atur);
        
    }
    
    void AksiTambah(){
        SIMPANEDIT = "Add";
//        noUrut();
        ID();
        bersih();
        tombol(false, true);
        AturText(true);
        bKeluar.setText("BATAL");
        //tbl_Simpanan.setVisible(false);
        txThr.setText("0");
        
    }
    
    void AksiEdit(){
        if(txKdSimpanan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Rubah");
        }
        else{
            SIMPANEDIT = "Edit";
            tombol(false, true);
            AturText(true);
            bKeluar.setText("BATAL");
            tbl_Simpanan.setVisible(false);
        }        
    }
    
    void AksiHapus(java.awt.event.ActionEvent evt){
        if(txKdSimpanan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di Hapus");
        }
        else{
            int selectedOption = JOptionPane.showConfirmDialog(null, "Yakin anda akan menghapus ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                try {
                    Statement statement=(Statement)Koneksi.GetConnection().createStatement();String sql = "DELETE FROM t_simpan WHERE kd_simpanan = '"+txKdSimpanan.getText()+"';";                    
                    statement.executeUpdate(sql);
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    TotalSaldo();
                    bersih();
                    tombol(true, false);
                    txKdSimpanan.setText("");
                } catch (Exception DBException) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus " + DBException);
                    bersih();
                }
            }            
            tampil();
        }
    }
    
    void AksiKeluar(java.awt.event.ActionEvent evt){
        if(bKeluar.getText().equals("KELUAR")){
            dispose();
        }
        else{
            AturText(false);
            bKeluar.setText("KELUAR");
            tombol(true, false);
            txKdSimpanan.setText("");
            tbl_Simpanan.setVisible(true);
            bersih();
        }
    }  
        
    public void itemTerpilih(){
        view_ang_simpan FVS = new view_ang_simpan(null, rootPaneCheckingEnabled);
        FVS.fAS=this;
        txID.setText(No_anggota);
        txNama.setText(Nama);
    }
    
    void AksiSimpanEdit(java.awt.event.ActionEvent evt){
        tbl_Simpanan.setVisible(true);
        
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(TxTglSim.getDate()));
        
        if (SIMPANEDIT.equalsIgnoreCase("Add")){
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "INSERT INTO t_simpan(kd_simpanan, No_anggota,Nama,Tgl_simpanan,THR,Saldo,Tot_saldo) "
                        + "VALUES ('"+txKdSimpanan.getText()+"','"+txID.getText()+"','"+txNama.getText()+"','"+tanggal+"','"+txThr.getText()+"','"+txSaldo.getText()+"','"+LTotal.getText()+"')";
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                TotalSaldo();
                txKdSimpanan.setText("");
                bersih();
                AturText(false);
                tombol(true, false);
                bKeluar.setText("KELUAR");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }
        }
        else{
            try {
                Statement statement=(Statement)Koneksi.GetConnection().createStatement();
                String sql = "UPDATE t_simpan SET No_anggota = '" +txID.getText()+"',"
                        + "Nama = '" + txNama.getText()+"',"
                        + "Tgl_simpanan= '" + tanggal +"',"
                        + "THR = '" + txThr.getText()+"',"
                        + "Saldo = '" + txSaldo.getText()+"',"
                        + "Tot_saldo = '" + LTotal.getText()+"'"
                        + "WHERE kd_simpanan = '"+txKdSimpanan.getText()+"'";                    
                statement.executeUpdate(sql);
                statement.close();
                tampil();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Rubah");
                TotalSaldo();
                bersih();
                AturText(false);
                tombol(true, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Rubah" + e);
            }
        }
    }
    
    void MouseClik(java.awt.event.MouseEvent evt){
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            int row = tbl_Simpanan.rowAtPoint(evt.getPoint());

            String kd_simpanan = tbl_Simpanan.getValueAt(row, 0).toString();
            String No_Anggota = tbl_Simpanan.getValueAt(row, 1).toString();
            String Nama = tbl_Simpanan.getValueAt(row, 2).toString();
            String Tgl_simpanan = tbl_Simpanan.getValueAt(row, 3).toString();
            String THR = tbl_Simpanan.getValueAt(row, 4).toString();
            String Saldo = tbl_Simpanan.getValueAt(row, 5).toString();
                        
            txKdSimpanan.setText(String.valueOf(kd_simpanan));
            txID.setText(String.valueOf(No_Anggota));
            txNama.setText(String.valueOf(Nama));
            TxTglSim.setDate(java.sql.Date.valueOf(Tgl_simpanan));
            txThr.setText(String.valueOf(THR));
            txSaldo.setText(String.valueOf(Saldo));
            } catch (Exception e) {
        }        
    }
    
    private void noUrut(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql ="SELECT MAX(right(kd_simpanan,1)) AS no FROM t_simpan";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first()==false){
                txKdSimpanan.setText("PJ-1");
            }
            else{
                rs.last();
                int no=rs.getInt(1)+1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i = 0; i < 2-pjg_cno; i++) {
                    cno=""+cno;
                }
                txKdSimpanan.setText("PJ-"+ cno);
            }
        } catch (Exception e) {
            System.err.println("Error = "+ e);
        }
    }
    
    void TotalSaldo(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("select SUM(THR) from t_simpan ");
            
            if (res.next()){
                String THR=res.getString("SUM(THR)");
                    
                LTotal.setText(THR);
                
            }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah" +e);
            }
    }
      
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
        }
    }
    
    void ID(){
        try {
            Statement statement=(Statement)Koneksi.GetConnection().createStatement();
            String sql = "SELECT MAX(right(kd_simpanan,5)) AS no FROM t_simpan";
            ResultSet rs = statement.executeQuery(sql);
            
            while(rs.next())
            {
                if(rs.first() == false)
                {
                txKdSimpanan.setText("SM-000001");
            }
                else
            {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<6-noLong;a++)
                    { 
                        no = "0" + no;
                    }
                   txKdSimpanan.setText("SM-" + no);
                 }        
            }
       rs.close();
        } catch (Exception e) {
        }
    }
}
